Repository OCA/multi-company, pull requests merged in 2020-04, with the labels that each got.

#196 [13.0][MIG] account_invoice_inter_company
  account_invoice_inter_company/README.rst
  account_invoice_inter_company/__init__.py
  account_invoice_inter_company/__manifest__.py
  account_invoice_inter_company/i18n/account_invoice_inter_company.pot
  account_invoice_inter_company/i18n/de.po
  account_invoice_inter_company/i18n/fr.po
  account_invoice_inter_company/i18n/hr.po
  account_invoice_inter_company/i18n/it.po
  account_invoice_inter_company/i18n/zh_CN.po
  account_invoice_inter_company/models/__init__.py
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/models/res_company.py
  account_invoice_inter_company/models/res_config_settings.py
  account_invoice_inter_company/readme/CONFIGURE.rst
  account_invoice_inter_company/readme/CONTRIBUTORS.rst
  account_invoice_inter_company/readme/DESCRIPTION.rst
  account_invoice_inter_company/readme/ROADMAP.rst
  account_invoice_inter_company/static/description/icon.png
  account_invoice_inter_company/static/description/index.html
  account_invoice_inter_company/tests/__init__.py
  account_invoice_inter_company/tests/inter_company_invoice.xml
  account_invoice_inter_company/tests/test_inter_company_invoice.py
  account_invoice_inter_company/views/res_config_settings_view.xml
  oca_dependencies.txt
  setup/account_invoice_inter_company/odoo/addons/account_invoice_inter_company
  setup/account_invoice_inter_company/setup.py
Labels: approved, bot is merging ⏳

#197 [13.0][MIG] base_multi_company
  base_multi_company/README.rst
  base_multi_company/__init__.py
  base_multi_company/__manifest__.py
  base_multi_company/hooks.py
  base_multi_company/i18n/base_multi_company.pot
  base_multi_company/i18n/es.po
  base_multi_company/i18n/fr.po
  base_multi_company/i18n/hr.po
  base_multi_company/i18n/nl_NL.po
  base_multi_company/i18n/pt.po
  base_multi_company/i18n/pt_BR.po
  base_multi_company/i18n/zh_CN.po
  base_multi_company/models/__init__.py
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/readme/CONTRIBUTORS.rst
  base_multi_company/readme/DESCRIPTION.rst
  base_multi_company/readme/USAGE.rst
  base_multi_company/static/description/icon.png
  base_multi_company/static/description/index.html
  base_multi_company/tests/__init__.py
  base_multi_company/tests/common.py
  base_multi_company/tests/multi_company_abstract_tester.py
  base_multi_company/tests/test_multi_company_abstract.py
  setup/base_multi_company/odoo/addons/base_multi_company
  setup/base_multi_company/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#184 [12.0][ADD] account_move_multi_company
  account_invoice_consolidated/models/account_invoice_consolidated.py
  account_invoice_consolidated/tests/test_consolidated_invoices_data.xml
  account_move_multi_company/README.rst
  account_move_multi_company/__init__.py
  account_move_multi_company/__manifest__.py
  account_move_multi_company/models/__init__.py
  account_move_multi_company/models/account_move.py
  account_move_multi_company/models/account_move_line.py
  account_move_multi_company/readme/CONFIGURE.rst
  account_move_multi_company/readme/CONTRIBUTORS.rst
  account_move_multi_company/readme/CREDITS.rst
  account_move_multi_company/readme/DESCRIPTION.rst
  account_move_multi_company/readme/USAGE.rst
  account_move_multi_company/security/ir_rule.xml
  account_move_multi_company/static/description/icon.png
  account_move_multi_company/static/description/index.html
  account_move_multi_company/tests/__init__.py
  account_move_multi_company/tests/test_account_move.py
  account_move_multi_company/views/account_move_view.xml
  base_multi_company/tests/test_multi_company_abstract.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#203 [FIX] account_payment_other_company: Apply the logic on post()
  account_payment_other_company/models/account_payment.py
  account_payment_other_company/tests/test_account_payment.py
  account_payment_other_company/views/account_payment.xml
Labels: approved, bot is merging ⏳, bug, needs review

#193 [11.0][FIX] account_multicompany_easy_creation: account code digits and currency ignored
  account_multicompany_easy_creation/README.rst
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
Labels: bot is merging ⏳
