Repository OCA/multi-company, pull requests merged in 2020-11, with the labels that each got.

#243 12.0 IMP Account_invoice_inter_company about shared catalog result
  account_invoice_inter_company/models/account_invoice.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#253 [FIX] account_invoice_intercompany: display lines
  account_invoice_inter_company/models/account_invoice.py
Labels: bot is merging ⏳

#247 [13.0][MIG] product_tax_multicompany_default: Migration to 13.0
  product_tax_multicompany_default/README.rst
  product_tax_multicompany_default/__init__.py
  product_tax_multicompany_default/__manifest__.py
  product_tax_multicompany_default/i18n/de.po
  product_tax_multicompany_default/i18n/es.po
  product_tax_multicompany_default/i18n/fr.po
  product_tax_multicompany_default/i18n/it.po
  product_tax_multicompany_default/i18n/product_tax_multicompany_default.pot
  product_tax_multicompany_default/models/__init__.py
  product_tax_multicompany_default/models/product.py
  product_tax_multicompany_default/readme/CONFIGURE.rst
  product_tax_multicompany_default/readme/CONTRIBUTORS.rst
  product_tax_multicompany_default/readme/DESCRIPTION.rst
  product_tax_multicompany_default/readme/USAGE.rst
  product_tax_multicompany_default/static/description/icon.png
  product_tax_multicompany_default/static/description/index.html
  product_tax_multicompany_default/tests/__init__.py
  product_tax_multicompany_default/tests/test_product_tax_multicompany.py
  product_tax_multicompany_default/views/product_template_view.xml
  setup/product_tax_multicompany_default/odoo/addons/product_tax_multicompany_default
  setup/product_tax_multicompany_default/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#255 [FIX] purchase_sale_inter_company: commitment_date
  purchase_sale_inter_company/models/purchase_order.py
Labels: approved, merged 🎉

#256 [FIX] purchase_sale_inter_company: commitment_date
  purchase_sale_inter_company/models/purchase_order.py
Labels: bot is merging ⏳
