Repository OCA/multi-company, pull requests merged in 2020-06, with the labels that each got.

#216 [IMP] account_move_multi_company: Copy Line Label to Other Journal Entries
  account_move_multi_company/models/account_move.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#223 [FIX] account_move_multi_company: Check ID in IF statement
  account_move_multi_company/models/account_move.py
Labels: approved, bot is merging ⏳, bug, needs review

#221 [13.0][IMP] account_invoice_inter_company: Remove onchange_helper dependency
  account_invoice_inter_company/README.rst
  account_invoice_inter_company/__manifest__.py
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/readme/CONTRIBUTORS.rst
  account_invoice_inter_company/static/description/index.html
  account_invoice_inter_company/tests/inter_company_invoice.xml
  account_invoice_inter_company/tests/test_inter_company_invoice.py
  account_invoice_inter_company/views/account_move_views.xml
Labels: approved, bot is merging ⏳, ready to merge
