Repository OCA/multi-company, pull requests merged in 2020-05, with the labels that each got.

#208 [IMP] account_move_multi_company: Allow easier extension to add other…
  account_move_multi_company/models/account_move.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#211 [IMP] account_payment_other_company: Flip Accounts For Vendor Refund
  account_payment_other_company/models/account_payment.py
Labels: approved, bot is merging ⏳, bug, needs review

#139 [12.0] - add multi-company management to calendar event
  calendar_event_multi_company/__init__.py
  calendar_event_multi_company/__manifest__.py
  calendar_event_multi_company/models/__init__.py
  calendar_event_multi_company/models/calendar_event.py
  calendar_event_multi_company/readme/CONTRIBUTORS.rst
  calendar_event_multi_company/readme/DESCRIPTION.rst
  calendar_event_multi_company/security/calendar_event.xml
  calendar_event_multi_company/views/calendar_event.xml
  setup/calendar_event_multi_company/odoo/addons/calendar_event_multi_company
  setup/calendar_event_multi_company/setup.py
Labels: approved, bot is merging ⏳, ready to merge
