Repository OCA/multi-company, pull requests merged in 2020-03, with the labels that each got.

#190 [11.0][FIX] partner_multi_company: If user switch company, don't delete user's partner's other companies
  partner_multi_company/models/res_users.py
Labels: approved

#124 [12.0] migrate product_multi_company
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/i18n/es.po
  product_multi_company/i18n/fr.po
  product_multi_company/i18n/hr.po
  product_multi_company/i18n/nl_NL.po
  product_multi_company/i18n/product_multi_company.pot
  product_multi_company/i18n/pt.po
  product_multi_company/models/__init__.py
  product_multi_company/models/product_template.py
  product_multi_company/readme/CONTRIBUTORS.rst
  product_multi_company/readme/DESCRIPTION.rst
  product_multi_company/readme/INSTALL.rst
  product_multi_company/readme/USAGE.rst
  product_multi_company/static/description/icon.png
  product_multi_company/static/description/index.html
  product_multi_company/tests/__init__.py
  product_multi_company/tests/test_product_multi_company.py
  product_multi_company/views/product_template_view.xml
Labels: approved, needs review, ready to merge

#173 [ADD] account_bill_line_distribution
  account_bill_line_distribution/README.rst
  account_bill_line_distribution/__init__.py
  account_bill_line_distribution/__manifest__.py
  account_bill_line_distribution/models/__init__.py
  account_bill_line_distribution/models/account_bill_line_distribution.py
  account_bill_line_distribution/models/account_invoice.py
  account_bill_line_distribution/models/account_invoice_line.py
  account_bill_line_distribution/readme/CONFIGURE.rst
  account_bill_line_distribution/readme/CONTRIBUTORS.rst
  account_bill_line_distribution/readme/DESCRIPTION.rst
  account_bill_line_distribution/readme/USAGE.rst
  account_bill_line_distribution/security/ir.model.access.csv
  account_bill_line_distribution/security/ir_rule.xml
  account_bill_line_distribution/static/description/icon.png
  account_bill_line_distribution/static/description/index.html
  account_bill_line_distribution/views/account_invoice.xml
  account_payment_other_company/tests/test_account_payment.py
  base_multi_company/tests/test_multi_company_abstract.py
Labels: approved, enhancement, needs review, ready to merge

#192 [FIX] account_payment_other_company: Sudo Search Read - "Search More" Option on Other Journal
  account_payment_other_company/models/account_journal.py
  account_payment_other_company/models/account_payment.py
Labels: approved, bug, ready to merge
