Repository OCA/multi-company, pull requests merged in 2020-08, with the labels that each got.

#195 [10.0] fix automated tests
  .travis.yml
  account_invoice_inter_company/models/account_invoice.py
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
  stock_production_lot_multi_company/tests/test_stock_production_lot_multi_company.py
Labels: approved, bot is merging ⏳, ready to merge

#238 12 IMP acc_inv_inter_cpny: detect intercompany with commercial_partner_id
  account_invoice_inter_company/models/account_invoice.py
  account_invoice_inter_company/readme/CONTRIBUTORS.rst
  account_invoice_inter_company/tests/inter_company_invoice.xml
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳

#239 13.0 IMP acc_inv_inter_cpny: detect intercompany with commercial_partner_id
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/readme/CONTRIBUTORS.rst
  account_invoice_inter_company/tests/inter_company_invoice.xml
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳

#118 [10.0][IMP] stock_production_lot_multi_company: Edit SQL constraint including company
  stock_production_lot_multi_company/__manifest__.py
  stock_production_lot_multi_company/models/stock_production_lot.py
Labels: approved
