Repository OCA/multi-company, pull requests merged in 2020-07, with the labels that each got.

#209 [13.0][FIX] account_invoice_inter_company: Solved problems for created invoices
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#231 [13.0][FIX] base_multi_company: incompatibility error
  base_multi_company/models/multi_company_abstract.py
Labels: approved, bot is merging ⏳

#189 [12.0] FIX account_invoice_inter_company config settings to make it work with remove_odoo_enterprise
  account_invoice_inter_company/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#198 [13.0][MIG] product_multi_company
  account_invoice_inter_company/tests/test_inter_company_invoice.py
  product_multi_company/README.rst
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/i18n/es.po
  product_multi_company/i18n/fr.po
  product_multi_company/i18n/hr.po
  product_multi_company/i18n/nl_NL.po
  product_multi_company/i18n/product_multi_company.pot
  product_multi_company/i18n/pt.po
  product_multi_company/migrations/13.0.1.0.0/pre-migration.py
  product_multi_company/models/__init__.py
  product_multi_company/models/product_category.py
  product_multi_company/models/product_template.py
  product_multi_company/readme/CONTRIBUTORS.rst
  product_multi_company/readme/DESCRIPTION.rst
  product_multi_company/readme/INSTALL.rst
  product_multi_company/readme/USAGE.rst
  product_multi_company/static/description/icon.png
  product_multi_company/static/description/index.html
  product_multi_company/tests/__init__.py
  product_multi_company/tests/test_product_multi_company.py
  product_multi_company/views/product_template_view.xml
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  setup/product_multi_company/odoo/addons/product_multi_company
  setup/product_multi_company/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#234 [13.0][FIX] base_multi_company: consider force_company context key.
  base_multi_company/models/multi_company_abstract.py
Labels: approved, bot is merging ⏳

#214 [13.0][ADD+MIG] mail multicompany
  mail_multicompany/README.rst
  mail_multicompany/__init__.py
  mail_multicompany/__manifest__.py
  mail_multicompany/models/__init__.py
  mail_multicompany/models/ir_mail_server.py
  mail_multicompany/models/mail_message.py
  mail_multicompany/readme/CONFIGURE.rst
  mail_multicompany/readme/CONTRIBUTORS.rst
  mail_multicompany/readme/DESCRIPTION.rst
  mail_multicompany/readme/USAGE.rst
  mail_multicompany/security/mail_security.xml
  mail_multicompany/tests/__init__.py
  mail_multicompany/tests/test_mail_multicompany.py
  mail_multicompany/views/ir_mail_server_view.xml
  setup/mail_multicompany/odoo/addons/mail_multicompany
  setup/mail_multicompany/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#224 [IMP] account_move_multi_company: Split Method
  account_move_multi_company/models/account_move.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
