Repository OCA/multi-company, pull requests merged in 2021-10, with the labels that each got.

#317 [13.0][FIX] account_multicompany_easy_creation: Apply the accounting template correctly + Tests
  account_multicompany_easy_creation/tests/__init__.py
  account_multicompany_easy_creation/tests/test_easy_creation.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
Labels: bot is merging ⏳

#321 [13.0][FIX] account_multicompany_easy_creation: Fix tests if l10n es previously installed.
  account_multicompany_easy_creation/tests/test_easy_creation.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
Labels: approved, bot is merging ⏳

#324 IMP inv_inter_cpny: add partner_shipping_id field
  account_invoice_inter_company/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳
