Repository OCA/multi-company, pull requests merged in 2021-07, with the labels that each got.

#175 [12.0] Add ir_filters_multi_company
  ir_filters_multi_company/__init__.py
  ir_filters_multi_company/__manifest__.py
  ir_filters_multi_company/hooks/post_init_hook.py
  ir_filters_multi_company/models/__init__.py
  ir_filters_multi_company/models/ir_filters.py
  ir_filters_multi_company/readme/CONTRIBUTORS.rst
  ir_filters_multi_company/readme/DESCRIPTION.rst
  ir_filters_multi_company/security/ir_filters.xml
  ir_filters_multi_company/views/ir_filters.xml
  setup/ir_filters_multi_company/odoo/addons/ir_filters_multi_company
  setup/ir_filters_multi_company/setup.py
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#301 [13.0][FIX] account_invoice_inter_company: post method
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#284 [14.0][MIG] account_invoice_consolidated
  account_invoice_consolidated/README.rst
  account_invoice_consolidated/__init__.py
  account_invoice_consolidated/__manifest__.py
  account_invoice_consolidated/data/account_invoice_consolidated_data.xml
  account_invoice_consolidated/i18n/account_invoice_consolidated.pot
  account_invoice_consolidated/i18n/pt.po
  account_invoice_consolidated/models/__init__.py
  account_invoice_consolidated/models/account_invoice_consolidated.py
  account_invoice_consolidated/models/account_move.py
  account_invoice_consolidated/models/account_move_line.py
  account_invoice_consolidated/models/account_payment.py
  account_invoice_consolidated/models/res_company.py
  account_invoice_consolidated/models/res_partner.py
  account_invoice_consolidated/readme/CONFIGURE.rst
  account_invoice_consolidated/readme/CONTRIBUTORS.rst
  account_invoice_consolidated/readme/CREDITS.rst
  account_invoice_consolidated/readme/DESCRIPTION.rst
  account_invoice_consolidated/readme/USAGE.rst
  account_invoice_consolidated/security/account_invoice_consolidated_security.xml
  account_invoice_consolidated/security/ir.model.access.csv
  account_invoice_consolidated/static/description/icon.png
  account_invoice_consolidated/static/description/index.html
  account_invoice_consolidated/tests/__init__.py
  account_invoice_consolidated/tests/test_consolidated_invoices.py
  account_invoice_consolidated/tests/test_consolidated_invoices_data.xml
  account_invoice_consolidated/views/account_invoice_consolidated_view.xml
  account_invoice_consolidated/views/account_move_view.xml
  account_invoice_consolidated/views/account_payment_view.xml
  account_invoice_consolidated/views/report_consolidated_invoice.xml
  account_invoice_consolidated/views/res_company_view.xml
  account_invoice_consolidated/views/res_partner_view.xml
  setup/account_invoice_consolidated/odoo/addons/account_invoice_consolidated
  setup/account_invoice_consolidated/setup.py
Labels: approved, bot is merging ⏳

#222 [12.0] IMP purchase_sale_inter_company allowing to create purchase orders from sales order
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/models/account_invoice.py
  purchase_sale_inter_company/models/purchase_order.py
  purchase_sale_inter_company/models/res_company.py
  purchase_sale_inter_company/models/res_config.py
  purchase_sale_inter_company/models/sale_order.py
  purchase_sale_inter_company/readme/CONFIGURE.rst
  purchase_sale_inter_company/readme/CONTRIBUTORS.rst
  purchase_sale_inter_company/readme/DESCRIPTION.rst
  purchase_sale_inter_company/tests/inter_company_purchase_sale.xml
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  purchase_sale_inter_company/views/res_config_view.xml
Labels: approved, bot is merging ⏳, ready to merge
