Repository OCA/multi-company, pull requests merged in 2021-11, with the labels that each got.

#318 [14.0] [MIG] account_multicompany_easy_creation
  account_multicompany_easy_creation/README.rst
  account_multicompany_easy_creation/__init__.py
  account_multicompany_easy_creation/__manifest__.py
  account_multicompany_easy_creation/i18n/account_multicompany_easy_creation.pot
  account_multicompany_easy_creation/i18n/es.po
  account_multicompany_easy_creation/readme/CONTRIBUTORS.rst
  account_multicompany_easy_creation/readme/DESCRIPTION.rst
  account_multicompany_easy_creation/readme/USAGE.rst
  account_multicompany_easy_creation/security/ir.model.access.csv
  account_multicompany_easy_creation/static/description/icon.png
  account_multicompany_easy_creation/static/description/index.html
  account_multicompany_easy_creation/tests/__init__.py
  account_multicompany_easy_creation/tests/test_easy_creation.py
  account_multicompany_easy_creation/wizards/__init__.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.xml
  setup/account_multicompany_easy_creation/odoo/addons/account_multicompany_easy_creation
  setup/account_multicompany_easy_creation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#315 [14.0] Add intercompany shared contact
  intercompany_shared_contact/README.rst
  intercompany_shared_contact/__init__.py
  intercompany_shared_contact/__manifest__.py
  intercompany_shared_contact/models/__init__.py
  intercompany_shared_contact/models/res_company.py
  intercompany_shared_contact/models/res_partner.py
  intercompany_shared_contact/models/res_users.py
  intercompany_shared_contact/readme/CONTRIBUTORS.rst
  intercompany_shared_contact/readme/DESCRIPTION.rst
  intercompany_shared_contact/readme/ROADMAP.rst
  intercompany_shared_contact/security/ir_rule.xml
  intercompany_shared_contact/tests/__init__.py
  intercompany_shared_contact/tests/test_shared_contacts.py
Labels: approved, ready to merge, bot is merging ⏳

#330 [14.0][FIX] account_invoice_inter_company: Delete default_journal_id if present
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#310 [MIG] res_company_code: migration to 14.0
  res_company_code/README.rst
  res_company_code/__init__.py
  res_company_code/__manifest__.py
  res_company_code/demo/res_company.xml
  res_company_code/demo/res_groups.xml
  res_company_code/i18n/es.po
  res_company_code/i18n/fr.po
  res_company_code/i18n/res_company_code.pot
  res_company_code/models/__init__.py
  res_company_code/models/ir_http.py
  res_company_code/models/res_company.py
  res_company_code/readme/CONTRIBUTORS.rst
  res_company_code/readme/DESCRIPTION.rst
  res_company_code/static/description/icon.png
  res_company_code/static/description/index.html
  res_company_code/static/description/res_company_form.png
  res_company_code/static/description/res_company_tree.png
  res_company_code/static/description/switch_company_menu.png
  res_company_code/tests/__init__.py
  res_company_code/tests/test_res_company_code.py
  res_company_code/views/view_res_company.xml
  setup/res_company_code/odoo/addons/res_company_code
  setup/res_company_code/setup.py
Labels: bot is merging ⏳
