Repository OCA/multi-company, pull requests merged in 2021-05, with the labels that each got.

#276 [13.0][FIX] purchase_sale_inter_company, PO->SO error when has line_section
  purchase_sale_inter_company/models/purchase_order.py
Labels: approved, bot is merging ⏳

#45 [10.0][MIG] port base_ir_filters_company to 10.0
  base_ir_filters_company/README.rst
  base_ir_filters_company/__init__.py
  base_ir_filters_company/__manifest__.py
  base_ir_filters_company/models/__init__.py
  base_ir_filters_company/models/ir_filters.py
  base_ir_filters_company/post_install.py
  base_ir_filters_company/security/base_ir_filters_company_security.xml
  base_ir_filters_company/views/ir_filters.xml
  setup/base_ir_filters_company/odoo/__init__.py
  setup/base_ir_filters_company/odoo/addons/__init__.py
  setup/base_ir_filters_company/odoo/addons/base_ir_filters_company
  setup/base_ir_filters_company/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#167 [12.0] [ADD] res_partner_industry_multi_company
  res_partner_industry_multi_company/__init__.py
  res_partner_industry_multi_company/__manifest__.py
  res_partner_industry_multi_company/models/__init__.py
  res_partner_industry_multi_company/models/res_partner_industry.py
  res_partner_industry_multi_company/readme/CONTRIBUTORS.rst
  res_partner_industry_multi_company/readme/DESCRIPTION.rst
  res_partner_industry_multi_company/security/res_partner_industry.xml
  res_partner_industry_multi_company/static/description/icon.png
  res_partner_industry_multi_company/views/res_partner_industry.xml
  setup/res_partner_industry_multi_company/odoo/addons/res_partner_industry_multi_company
  setup/res_partner_industry_multi_company/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#273 14.0 [MIG] OCA: mail_multicompany
  mail_multicompany/README.rst
  mail_multicompany/__init__.py
  mail_multicompany/__manifest__.py
  mail_multicompany/i18n/es.po
  mail_multicompany/i18n/mail_multicompany.pot
  mail_multicompany/models/__init__.py
  mail_multicompany/models/ir_mail_server.py
  mail_multicompany/models/mail_message.py
  mail_multicompany/readme/CONFIGURE.rst
  mail_multicompany/readme/CONTRIBUTORS.rst
  mail_multicompany/readme/DESCRIPTION.rst
  mail_multicompany/readme/USAGE.rst
  mail_multicompany/security/mail_security.xml
  mail_multicompany/static/description/icon.png
  mail_multicompany/static/description/index.html
  mail_multicompany/tests/__init__.py
  mail_multicompany/tests/test_mail_multicompany.py
  mail_multicompany/views/ir_mail_server_view.xml
  setup/mail_multicompany/odoo/addons/mail_multicompany
  setup/mail_multicompany/setup.py
Labels: bot is merging ⏳

#236 [10.0][MIG] Backport mail_template_multi_company (from 12.0)
  mail_template_multi_company/README.rst
  mail_template_multi_company/__init__.py
  mail_template_multi_company/__manifest__.py
  mail_template_multi_company/i18n/mail_template_multi_company.pot
  mail_template_multi_company/models/__init__.py
  mail_template_multi_company/models/mail_template.py
  mail_template_multi_company/readme/CONFIGURE.rst
  mail_template_multi_company/readme/CONTRIBUTORS.rst
  mail_template_multi_company/readme/DESCRIPTION.rst
  mail_template_multi_company/readme/USAGE.rst
  mail_template_multi_company/security/mail_template.xml
  mail_template_multi_company/static/description/icon.png
  mail_template_multi_company/static/description/index.html
  mail_template_multi_company/views/mail_template.xml
  setup/mail_template_multi_company/odoo/__init__.py
  setup/mail_template_multi_company/odoo/addons/__init__.py
  setup/mail_template_multi_company/odoo/addons/mail_template_multi_company
  setup/mail_template_multi_company/setup.py
Labels: approved, bot is merging ⏳, ready to merge
