Repository OCA/multi-company, pull requests merged in 2021-09, with the labels that each got.

#312 [FIX] account_invoice_inter_company: Fix migration
  account_invoice_inter_company/migrations/13.0.1.0.0/post-migration.py
Labels: approved

#307 [12.0][IMP] puchase_sale_inter_company: option not to overwrite PO prices
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/models/res_company.py
  purchase_sale_inter_company/models/res_config.py
  purchase_sale_inter_company/models/sale_order.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  purchase_sale_inter_company/views/res_config_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#313 [13.0][FIX] base_multi_company: Make company_id writeable again
  base_multi_company/models/multi_company_abstract.py
Labels: approved, bot is merging ⏳

#314 [13.0][FIX] account_multicompany_easy_creation: Remove duplicate company creation.
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
Labels: bot is merging ⏳
