Repository OCA/multi-company, pull requests merged in 2021-01, with the labels that each got.

#232 [13.0][MIG] mail_template_multi_company
  mail_template_multi_company/README.rst
  mail_template_multi_company/__init__.py
  mail_template_multi_company/__manifest__.py
  mail_template_multi_company/i18n/mail_template_multi_company.pot
  mail_template_multi_company/migrations/13.0.1.0.0/post-migration.py
  mail_template_multi_company/models/__init__.py
  mail_template_multi_company/models/mail_template.py
  mail_template_multi_company/readme/CONFIGURE.rst
  mail_template_multi_company/readme/CONTRIBUTORS.rst
  mail_template_multi_company/readme/DESCRIPTION.rst
  mail_template_multi_company/readme/USAGE.rst
  mail_template_multi_company/security/mail_template.xml
  mail_template_multi_company/static/description/icon.png
  mail_template_multi_company/static/description/index.html
  mail_template_multi_company/views/mail_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#265 [FIX] product_multi_company: integrate tests with product_variant_configurator
  product_multi_company/tests/test_product_multi_company.py
Labels: approved, bot is merging ⏳

#266 [13.0][MIG] partner_multi_company: Migration to 13.0
  base_multi_company/models/multi_company_abstract.py
  partner_multi_company/README.rst
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/i18n/de.po
  partner_multi_company/i18n/es.po
  partner_multi_company/i18n/fr.po
  partner_multi_company/i18n/hr.po
  partner_multi_company/i18n/partner_multi_company.pot
  partner_multi_company/i18n/pt.po
  partner_multi_company/migrations/13.0.1.0.0/pre-migration.py
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/models/res_users.py
  partner_multi_company/readme/CONTRIBUTORS.rst
  partner_multi_company/readme/DESCRIPTION.rst
  partner_multi_company/readme/INSTALL.rst
  partner_multi_company/readme/ROADMAP.rst
  partner_multi_company/readme/USAGE.rst
  partner_multi_company/static/description/icon.png
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/__init__.py
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_partner_view.xml
  setup/partner_multi_company/odoo/addons/partner_multi_company
  setup/partner_multi_company/setup.py
Labels: bot is merging ⏳
