Repository OCA/multi-company, pull requests merged in 2022-04, with the labels that each got.

#271 [14.0][MIG] product_multi_company
  product_multi_company/README.rst
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/i18n/es.po
  product_multi_company/i18n/fr.po
  product_multi_company/i18n/hr.po
  product_multi_company/i18n/nl_NL.po
  product_multi_company/i18n/product_multi_company.pot
  product_multi_company/i18n/pt.po
  product_multi_company/models/__init__.py
  product_multi_company/models/product_category.py
  product_multi_company/models/product_template.py
  product_multi_company/readme/CONTRIBUTORS.rst
  product_multi_company/readme/DESCRIPTION.rst
  product_multi_company/readme/INSTALL.rst
  product_multi_company/readme/USAGE.rst
  product_multi_company/static/description/icon.png
  product_multi_company/static/description/index.html
  product_multi_company/tests/__init__.py
  product_multi_company/tests/common.py
  product_multi_company/tests/test_product_multi_company.py
  product_multi_company/views/product_template_view.xml
  setup/product_multi_company/odoo/addons/product_multi_company
  setup/product_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#352 [14][account_invoice_inter_company] Add compatibility with modules sale and account_invoice_start_end_dates
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#342 [FIX] fix editing bank_ids fields
  intercompany_shared_contact/models/res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#322 [FIX] account_invoice_intercompany: Force no default journal
  account_invoice_inter_company/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#348 [15.0] [MIG] product_multi_company
  product_multi_company/README.rst
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/i18n/es.po
  product_multi_company/i18n/fr.po
  product_multi_company/i18n/hr.po
  product_multi_company/i18n/nl_NL.po
  product_multi_company/i18n/product_multi_company.pot
  product_multi_company/i18n/pt.po
  product_multi_company/models/__init__.py
  product_multi_company/models/product_category.py
  product_multi_company/models/product_template.py
  product_multi_company/readme/CONTRIBUTORS.rst
  product_multi_company/readme/DESCRIPTION.rst
  product_multi_company/readme/INSTALL.rst
  product_multi_company/readme/USAGE.rst
  product_multi_company/static/description/icon.png
  product_multi_company/static/description/index.html
  product_multi_company/tests/__init__.py
  product_multi_company/tests/common.py
  product_multi_company/tests/test_product_multi_company.py
  product_multi_company/views/product_template_view.xml
  setup/product_multi_company/odoo/addons/product_multi_company
  setup/product_multi_company/setup.py
Labels: bot is merging ⏳

#350 [15.0][MIG] partner_multi_company
  partner_multi_company/README.rst
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/i18n/de.po
  partner_multi_company/i18n/es.po
  partner_multi_company/i18n/fr.po
  partner_multi_company/i18n/hr.po
  partner_multi_company/i18n/partner_multi_company.pot
  partner_multi_company/i18n/pt.po
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/models/res_users.py
  partner_multi_company/readme/CONTRIBUTORS.rst
  partner_multi_company/readme/DESCRIPTION.rst
  partner_multi_company/readme/INSTALL.rst
  partner_multi_company/readme/ROADMAP.rst
  partner_multi_company/readme/USAGE.rst
  partner_multi_company/static/description/icon.png
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/__init__.py
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_partner_view.xml
  setup/partner_multi_company/odoo/addons/partner_multi_company
  setup/partner_multi_company/setup.py
Labels: bot is merging ⏳
