Repository OCA/multi-company, pull requests merged in 2022-08, with the labels that each got.

#372 [14.0][ADD] account_invoice_inter_company_queued
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/views/res_config_settings_view.xml
  account_invoice_inter_company_queued/README.rst
  account_invoice_inter_company_queued/__init__.py
  account_invoice_inter_company_queued/__manifest__.py
  account_invoice_inter_company_queued/models/__init__.py
  account_invoice_inter_company_queued/models/account_move.py
  account_invoice_inter_company_queued/models/res_config_settings.py
  account_invoice_inter_company_queued/readme/CONFIGURE.rst
  account_invoice_inter_company_queued/readme/CONTRIBUTORS.rst
  account_invoice_inter_company_queued/readme/DESCRIPTION.rst
  account_invoice_inter_company_queued/views/res_config_settings_view.xml
  setup/account_invoice_inter_company_queued/odoo/addons/account_invoice_inter_company_queued
  setup/account_invoice_inter_company_queued/setup.py
Labels: approved, bot is merging ⏳

#340 [MIG][14.0] product_tax_multicompany_default
  product_tax_multicompany_default/README.rst
  product_tax_multicompany_default/__init__.py
  product_tax_multicompany_default/__manifest__.py
  product_tax_multicompany_default/i18n/de.po
  product_tax_multicompany_default/i18n/es.po
  product_tax_multicompany_default/i18n/fr.po
  product_tax_multicompany_default/i18n/it.po
  product_tax_multicompany_default/i18n/product_tax_multicompany_default.pot
  product_tax_multicompany_default/models/__init__.py
  product_tax_multicompany_default/models/product.py
  product_tax_multicompany_default/readme/CONFIGURE.rst
  product_tax_multicompany_default/readme/CONTRIBUTORS.rst
  product_tax_multicompany_default/readme/DESCRIPTION.rst
  product_tax_multicompany_default/readme/USAGE.rst
  product_tax_multicompany_default/static/description/icon.png
  product_tax_multicompany_default/static/description/index.html
  product_tax_multicompany_default/tests/__init__.py
  product_tax_multicompany_default/tests/test_product_tax_multicompany.py
  product_tax_multicompany_default/views/product_template_view.xml
  setup/product_tax_multicompany_default/odoo/addons/product_tax_multicompany_default
  setup/product_tax_multicompany_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#296 [14.0] purchase_quick_intercompany: add
  oca_dependencies.txt
  purchase_quick_intercompany/README.rst
  purchase_quick_intercompany/__init__.py
  purchase_quick_intercompany/__manifest__.py
  purchase_quick_intercompany/i18n/fr.po
  purchase_quick_intercompany/models/__init__.py
  purchase_quick_intercompany/models/product_product.py
  purchase_quick_intercompany/models/product_template.py
  purchase_quick_intercompany/readme/CONTRIBUTORS.rst
  purchase_quick_intercompany/readme/DESCRIPTION.rst
  purchase_quick_intercompany/readme/USAGE.rst
  purchase_quick_intercompany/static/description/icon.png
  purchase_quick_intercompany/tests/__init__.py
  purchase_quick_intercompany/tests/test_purchase_quick_intercompany.py
  purchase_quick_intercompany/views/product_template_view.xml
  purchase_quick_intercompany/views/product_view.xml
  setup/purchase_quick_intercompany/odoo/addons/purchase_quick_intercompany
  setup/purchase_quick_intercompany/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#316 [14.0] purchase_sale_inter_company clean test and fix
  purchase_sale_inter_company/models/account_move.py
  purchase_sale_inter_company/models/purchase_order.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: needs review, approved, bot is merging ⏳

#344 [14.0][ADD] product_category_inter_company module
  product_category_inter_company/__init__.py
  product_category_inter_company/__manifest__.py
  product_category_inter_company/i18n/fr.po
  product_category_inter_company/models/__init__.py
  product_category_inter_company/models/product_category.py
  product_category_inter_company/models/product_template.py
  product_category_inter_company/readme/CONTRIBUTORS.rst
  product_category_inter_company/readme/DESCRIPTION.rst
  product_category_inter_company/security/ir_rule.xml
  product_category_inter_company/tests/__init__.py
  product_category_inter_company/tests/test_product_category.py
  product_category_inter_company/views/product_category.xml
  product_category_inter_company/views/product_template_view.xml
  setup/product_category_inter_company/odoo/addons/product_category_inter_company
  setup/product_category_inter_company/setup.py
Labels: approved, bot is merging ⏳
