Repository OCA/multi-company, pull requests merged in 2022-12, with the labels that each got.

#419 [13.0][FIX] account_invoice_inter_company : run test at post install
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: bot is merging ⏳

#422 [15.0][FIX] base_multi_company: move test dependency to test-requirements
  base_multi_company/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#401 [ADD] account_change_company
  account_move_change_company/README.rst
  account_move_change_company/__init__.py
  account_move_change_company/__manifest__.py
  account_move_change_company/models/__init__.py
  account_move_change_company/models/account_move.py
  account_move_change_company/readme/CONTRIBUTORS.rst
  account_move_change_company/readme/DESCRIPTION.rst
  account_move_change_company/static/description/icon.png
  account_move_change_company/static/description/index.html
  account_move_change_company/tests/__init__.py
  account_move_change_company/tests/test_change_company.py
  account_move_change_company/views/account_move.xml
  setup/account_move_change_company/odoo/addons/account_move_change_company
  setup/account_move_change_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#411 [MIG][14.0] partner_multi_company
  partner_multi_company/README.rst
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/i18n/de.po
  partner_multi_company/i18n/es.po
  partner_multi_company/i18n/fr.po
  partner_multi_company/i18n/hr.po
  partner_multi_company/i18n/partner_multi_company.pot
  partner_multi_company/i18n/pt.po
  partner_multi_company/migrations/13.0.1.0.0/pre-migration.py
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/models/res_users.py
  partner_multi_company/readme/CONTRIBUTORS.rst
  partner_multi_company/readme/DESCRIPTION.rst
  partner_multi_company/readme/INSTALL.rst
  partner_multi_company/readme/ROADMAP.rst
  partner_multi_company/readme/USAGE.rst
  partner_multi_company/static/description/icon.png
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/__init__.py
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_partner_view.xml
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  setup/partner_multi_company/odoo/addons/partner_multi_company
  setup/partner_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#407 [ADD] multicompany_configuration
  multicompany_configuration/README.rst
  multicompany_configuration/__init__.py
  multicompany_configuration/__manifest__.py
  multicompany_configuration/models/__init__.py
  multicompany_configuration/models/multicompany_abstract.py
  multicompany_configuration/models/product_category.py
  multicompany_configuration/models/product_template.py
  multicompany_configuration/models/res_partner.py
  multicompany_configuration/readme/CONTRIBUTORS.rst
  multicompany_configuration/readme/DESCRIPTION.rst
  multicompany_configuration/static/description/icon.png
  multicompany_configuration/static/src/js/multicompany_data_field.js
  multicompany_configuration/static/src/scss/multicompany_data_field.scss
  multicompany_configuration/templates/assets.xml
  multicompany_configuration/views/product_category.xml
  multicompany_configuration/views/product_product.xml
  multicompany_configuration/views/product_template.xml
  multicompany_configuration/views/res_partner.xml
  setup/multicompany_configuration/odoo/addons/multicompany_configuration
  setup/multicompany_configuration/setup.py
Labels: approved, bot is merging ⏳

#406 [15.0][MIG] account_multicompany_easy_creation: Migration to 15.0
  account_multicompany_easy_creation/README.rst
  account_multicompany_easy_creation/__init__.py
  account_multicompany_easy_creation/__manifest__.py
  account_multicompany_easy_creation/i18n/account_multicompany_easy_creation.pot
  account_multicompany_easy_creation/i18n/es.po
  account_multicompany_easy_creation/readme/CONTRIBUTORS.rst
  account_multicompany_easy_creation/readme/DESCRIPTION.rst
  account_multicompany_easy_creation/readme/USAGE.rst
  account_multicompany_easy_creation/security/ir.model.access.csv
  account_multicompany_easy_creation/static/description/icon.png
  account_multicompany_easy_creation/static/description/index.html
  account_multicompany_easy_creation/tests/__init__.py
  account_multicompany_easy_creation/tests/test_easy_creation.py
  account_multicompany_easy_creation/wizards/__init__.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.xml
  setup/account_multicompany_easy_creation/odoo/addons/account_multicompany_easy_creation
  setup/account_multicompany_easy_creation/setup.py
Labels: approved, bot is merging ⏳
