Repository OCA/multi-company, pull requests merged in 2022-09, with the labels that each got.

#361 [14.0][IMP] account_invoice_inter_company: Speed improvement
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#374 [14.0][IMP] product_supplierinfo_intercompany: create intercompany pr…
  product_supplierinfo_intercompany/models/product_pricelist_item.py
  product_supplierinfo_intercompany/models/product_template.py
  product_supplierinfo_intercompany/readme/ROADMAP.rst
  product_supplierinfo_intercompany/tests/test_supplier_intercompany.py
Labels: approved, ready to merge, bot is merging ⏳

#377 [14.0][IMP] account_invoice_inter_company: added multi company tab
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/readme/CONTRIBUTORS.rst
  account_invoice_inter_company/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#381 [14.0][FIX] account_invoice_inter_company: Intercompany should be vis…
  account_invoice_inter_company/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#378 [14.0][FIX] account_invoice_inter_company_queued: check record exists…
  account_invoice_inter_company_queued/models/account_move.py
Labels: approved, bot is merging ⏳

#380 [14.0][ADD] account_invoice_inter_company_sale
  account_invoice_inter_company_sale/README.rst
  account_invoice_inter_company_sale/__init__.py
  account_invoice_inter_company_sale/__manifest__.py
  account_invoice_inter_company_sale/models/__init__.py
  account_invoice_inter_company_sale/models/account_move.py
  account_invoice_inter_company_sale/readme/CONFIGURE.rst
  account_invoice_inter_company_sale/readme/CONTRIBUTORS.rst
  account_invoice_inter_company_sale/readme/DESCRIPTION.rst
  account_invoice_inter_company_sale/readme/ROADMAP.rst
  account_invoice_inter_company_sale/views/account_move_views.xml
  setup/account_invoice_inter_company_sale/odoo/addons/account_invoice_inter_company_sale
  setup/account_invoice_inter_company_sale/setup.py
Labels: approved, bot is merging ⏳

#385 [14.0][FIX] account_invoice_consolidated: add migration script
  account_invoice_consolidated/__manifest__.py
  account_invoice_consolidated/migrations/14.0.1.0.1/post-migrate.py
Labels: bot is merging ⏳
