Repository OCA/multi-company, pull requests merged in 2023-01, with the labels that each got.

#370 [ADD][15.0] `purchase_sale_inter_company` without dependency on `stock`
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/__init__.py
  purchase_sale_inter_company/__manifest__.py
  purchase_sale_inter_company/i18n/de.po
  purchase_sale_inter_company/i18n/es.po
  purchase_sale_inter_company/i18n/fr.po
  purchase_sale_inter_company/i18n/fr_FR.po
  purchase_sale_inter_company/i18n/it.po
  purchase_sale_inter_company/i18n/purchase_sale_inter_company.pot
  purchase_sale_inter_company/i18n/sl.po
  purchase_sale_inter_company/i18n/zh_CN.po
  purchase_sale_inter_company/models/__init__.py
  purchase_sale_inter_company/models/account_move.py
  purchase_sale_inter_company/models/purchase_order.py
  purchase_sale_inter_company/models/res_company.py
  purchase_sale_inter_company/models/res_config.py
  purchase_sale_inter_company/models/sale_order.py
  purchase_sale_inter_company/readme/CONFIGURE.rst
  purchase_sale_inter_company/readme/CONTRIBUTORS.rst
  purchase_sale_inter_company/readme/DESCRIPTION.rst
  purchase_sale_inter_company/readme/ROADMAP.rst
  purchase_sale_inter_company/static/description/icon.png
  purchase_sale_inter_company/tests/__init__.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  purchase_sale_inter_company/views/res_config_view.xml
  setup/purchase_sale_inter_company/odoo/addons/purchase_sale_inter_company
  setup/purchase_sale_inter_company/setup.py
Labels: approved, bot is merging ⏳

#412 product_supplierinfo_group_intercompany: fix broken update of supplierinfo
  product_supplierinfo_group_intercompany/__manifest__.py
  product_supplierinfo_group_intercompany/migrations/14.0.1.1.0/post-fix-data.py
  product_supplierinfo_group_intercompany/models/product_supplierinfo.py
  product_supplierinfo_group_intercompany/tests/test_product_supplerinfo_group.py
  product_supplierinfo_intercompany/models/product_supplierinfo.py
  product_supplierinfo_intercompany/tests/test_supplier_intercompany.py
Labels: bot is merging ⏳

#429 12.0 ref add copier template
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_invoice_consolidated/__manifest__.py
  partner_multi_company/__manifest__.py
  product_intercompany_account/__manifest__.py
  product_tax_multicompany_default/__manifest__.py
  purchase_sale_inter_company/__manifest__.py
  res_partner_industry_multi_company/__manifest__.py
Labels: approved, bot is merging ⏳

#354 [14.0][IMP] base_multi_company: Don't set default on company_ids
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
  product_multi_company/tests/test_product_multi_company.py
Labels: approved, bot is merging ⏳

#309 [14.0] add stock_intercompany module
  setup/stock_intercompany/odoo/addons/stock_intercompany
  setup/stock_intercompany/setup.py
  stock_intercompany/__init__.py
  stock_intercompany/__manifest__.py
  stock_intercompany/models/__init__.py
  stock_intercompany/models/res_company.py
  stock_intercompany/models/res_config_settings.py
  stock_intercompany/models/stock_picking.py
  stock_intercompany/readme/CONFIGURE.rst
  stock_intercompany/readme/CONTRIBUTORS.rst
  stock_intercompany/readme/DESCRIPTION.rst
  stock_intercompany/tests/__init__.py
  stock_intercompany/tests/test_intercompany_picking.py
  stock_intercompany/views/res_config_settings.xml
Labels: bot is merging ⏳, no stale

#432 [16.0] [MIG] product_tax_multicompany_default
  product_tax_multicompany_default/README.rst
  product_tax_multicompany_default/__init__.py
  product_tax_multicompany_default/__manifest__.py
  product_tax_multicompany_default/i18n/de.po
  product_tax_multicompany_default/i18n/es.po
  product_tax_multicompany_default/i18n/fr.po
  product_tax_multicompany_default/i18n/it.po
  product_tax_multicompany_default/i18n/product_tax_multicompany_default.pot
  product_tax_multicompany_default/models/__init__.py
  product_tax_multicompany_default/models/product.py
  product_tax_multicompany_default/readme/CONFIGURE.rst
  product_tax_multicompany_default/readme/CONTRIBUTORS.rst
  product_tax_multicompany_default/readme/DESCRIPTION.rst
  product_tax_multicompany_default/readme/USAGE.rst
  product_tax_multicompany_default/static/description/icon.png
  product_tax_multicompany_default/static/description/index.html
  product_tax_multicompany_default/tests/__init__.py
  product_tax_multicompany_default/tests/test_product_tax_multicompany.py
  product_tax_multicompany_default/views/product_template_view.xml
  setup/product_tax_multicompany_default/odoo/addons/product_tax_multicompany_default
  setup/product_tax_multicompany_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#434 [14.0][FIX] account_payment_other_company: fix force_company
  account_payment_other_company/models/account_payment.py
Labels: approved, bot is merging ⏳
