Repository OCA/multi-company, pull requests merged in 2023-06, with the labels that each got.

#425 [16.0] [MIG] account_multicompany_easy_creation
  account_multicompany_easy_creation/README.rst
  account_multicompany_easy_creation/__init__.py
  account_multicompany_easy_creation/__manifest__.py
  account_multicompany_easy_creation/i18n/account_multicompany_easy_creation.pot
  account_multicompany_easy_creation/i18n/es.po
  account_multicompany_easy_creation/readme/CONTRIBUTORS.rst
  account_multicompany_easy_creation/readme/DESCRIPTION.rst
  account_multicompany_easy_creation/readme/USAGE.rst
  account_multicompany_easy_creation/security/ir.model.access.csv
  account_multicompany_easy_creation/static/description/icon.png
  account_multicompany_easy_creation/static/description/index.html
  account_multicompany_easy_creation/tests/__init__.py
  account_multicompany_easy_creation/tests/test_easy_creation.py
  account_multicompany_easy_creation/wizards/__init__.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.xml
  setup/account_multicompany_easy_creation/odoo/addons/account_multicompany_easy_creation
  setup/account_multicompany_easy_creation/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#462 [IMP] account_invoice_inter_company add index
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#488 [15.0][FIX] account_invoice_inter_company: post dest invoice
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#489 [15.0][FIX] account_invoice_inter_company: Avoid crash on False dest_company
  account_invoice_inter_company/models/account_move.py
Labels: bot is merging ⏳

#427 [ADD] login_all_company
  login_all_company/README.rst
  login_all_company/__init__.py
  login_all_company/__manifest__.py
  login_all_company/readme/CONTRIBUTORS.rst
  login_all_company/readme/DESCRIPTION.rst
  login_all_company/static/description/icon.png
  login_all_company/static/description/index.html
  login_all_company/static/src/js/client.js
  login_all_company/templates/assets.xml
  setup/login_all_company/odoo/addons/login_all_company
  setup/login_all_company/setup.py
Labels: approved, bot is merging ⏳
