Repository OCA/multi-company, pull requests merged in 2023-10, with the labels that each got.

#511 [14.0] Update copier & pre-commit
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_invoice_consolidated/tests/test_consolidated_invoices_data.xml
  account_payment_other_company/tests/test_account_payment_data.xml
  intercompany_shared_contact/security/ir_rule.xml
  login_all_company/templates/assets.xml
  product_supplierinfo_group_intercompany/security/ir_rule.xml
  product_supplierinfo_intercompany/demo/pricelist.xml
  product_supplierinfo_intercompany/security/supplierinfo.xml
  product_supplierinfo_intercompany/views/pricelist_views.xml
Labels: bot is merging ⏳

#519 [FIX] mail_multicompany: Fix super to create the messages
  mail_multicompany/models/mail_message.py
Labels: approved, bot is merging ⏳

#461 [14.0] account_invoice_inter_company: use the right company for call the pdf generation
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#480 [14.0] product_category_inter_company: fix constraint
  product_category_inter_company/models/product_category.py
Labels: bot is merging ⏳, stale

#524 [14.0] [REL] purchase_sale_inter_company: Generate new major version
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/__manifest__.py
  purchase_sale_inter_company/static/description/index.html
Labels: bot is merging ⏳

#527 [14.0] [FIX] github pre-commit action: pin python version to 3.11 in repository
  .github/workflows/pre-commit.yml
Labels: bot is merging ⏳

#526 [14.0] [FIX] account_invoice_inter_company: Remove self company from eligible companies in `_find_company_from_invoice_partner`
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳

#428 [12.0][ADD] product_category_company_favorite module
  product_category_company_favorite/README.rst
  product_category_company_favorite/__init__.py
  product_category_company_favorite/__manifest__.py
  product_category_company_favorite/demo/res_company.xml
  product_category_company_favorite/i18n/fr.po
  product_category_company_favorite/models/__init__.py
  product_category_company_favorite/models/product_category.py
  product_category_company_favorite/models/res_company.py
  product_category_company_favorite/post_init_hook.py
  product_category_company_favorite/readme/CONFIGURE.rst
  product_category_company_favorite/readme/CONTRIBUTORS.rst
  product_category_company_favorite/readme/DESCRIPTION.rst
  product_category_company_favorite/readme/ROADMAP.rst
  product_category_company_favorite/readme/USAGE.rst
  product_category_company_favorite/static/description/product_category_tree.png
  product_category_company_favorite/static/description/product_form_view.png
  product_category_company_favorite/tests/__init__.py
  product_category_company_favorite/tests/test_module.py
  product_category_company_favorite/views/view_product_category.xml
  setup/product_category_company_favorite/odoo/addons/product_category_company_favorite
  setup/product_category_company_favorite/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#528 [13.0][FIX] account_invoice_inter_company: Check the product with proper company context
  account_invoice_inter_company/models/account_move.py
Labels: approved, bot is merging ⏳
