Repository OCA/multi-company, pull requests merged in 2023-04, with the labels that each got.

#469 [IMP] product_tax_multicompany_default: beautier and mass propagation
  product_tax_multicompany_default/models/product.py
  product_tax_multicompany_default/readme/USAGE.rst
  product_tax_multicompany_default/tests/test_product_tax_multicompany.py
  product_tax_multicompany_default/views/product_template_view.xml
Labels: bot is merging ⏳

#468 [IMP] product_tax_multicompany_default: beautier and mass propagation
  product_tax_multicompany_default/models/product.py
  product_tax_multicompany_default/readme/USAGE.rst
  product_tax_multicompany_default/tests/test_product_tax_multicompany.py
  product_tax_multicompany_default/views/product_template_view.xml
Labels: bot is merging ⏳

#474 [12.0][FIX] product_intercompany_account: sudo when searching companies
  product_intercompany_account/models/account_invoice.py
  product_intercompany_account/models/account_invoice_line.py
  product_intercompany_account/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#390 [16.0][ADD] res_company_search_view
  res_company_search_view/README.rst
  res_company_search_view/__init__.py
  res_company_search_view/__manifest__.py
  res_company_search_view/i18n/fr.po
  res_company_search_view/readme/CONTRIBUTORS.rst
  res_company_search_view/readme/DESCRIPTION.rst
  res_company_search_view/views/view_res_company.xml
  setup/res_company_search_view/odoo/addons/res_company_search_view
  setup/res_company_search_view/setup.py
Labels: approved, bot is merging ⏳

#467 [16.0][FIX] product_tax_multicompany_default: supplier_taxes_id was not found in the form view during tests
  product_tax_multicompany_default/__manifest__.py
  product_tax_multicompany_default/tests/test_product_tax_multicompany.py
Labels: approved, ready to merge

#470 [16.0][MIG] product_category[_inter]_company
  .oca/oca-port/blacklist/product_category_inter_company.json
  product_category_company/README.rst
  product_category_company/__init__.py
  product_category_company/__manifest__.py
  product_category_company/i18n/fr.po
  product_category_company/i18n/product_category_company.pot
  product_category_company/models/__init__.py
  product_category_company/models/product_category.py
  product_category_company/readme/CONTRIBUTORS.rst
  product_category_company/readme/DESCRIPTION.rst
  product_category_company/security/ir_rule.xml
  product_category_company/static/description/icon.png
  product_category_company/static/description/index.html
  product_category_company/tests/__init__.py
  product_category_company/tests/test_product_category.py
  product_category_company/views/product_category.xml
  product_category_company/views/product_template_view.xml
  setup/product_category_company/odoo/addons/product_category_company
  setup/product_category_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳
