Repository OCA/multi-company, pull requests merged in 2023-11, with the labels that each got.

#525 [14.0][FIX] when action post an auto_generated invoice browse not made with sudo leads to access rights issues on origin invoice
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#532 [16.0] [FIX] account_invoice_inter_company: Remove self company from eligible companies in `_find_company_from_invoice_partner`
  account_invoice_inter_company/models/account_move.py
Labels: bot is merging ⏳

#531 [15.0] [FIX] account_invoice_inter_company: Remove self company from eligible companies in `_find_company_from_invoice_partner`
  account_invoice_inter_company/models/account_move.py
Labels: bot is merging ⏳

#535 [14.0][FIX] base_multi_company: Proper _check_company when multiple companies selected
  base_multi_company/models/__init__.py
  base_multi_company/models/base.py
  base_multi_company/models/multi_company_abstract.py
Labels: approved, bot is merging ⏳
