Repository OCA/multi-company, pull requests merged in 2023-08, with the labels that each got.

#498 [16.0][MIG] mail_template_multi_company: Migration to 16.0
  mail_template_multi_company/README.rst
  mail_template_multi_company/__init__.py
  mail_template_multi_company/__manifest__.py
  mail_template_multi_company/i18n/es.po
  mail_template_multi_company/i18n/mail_template_multi_company.pot
  mail_template_multi_company/i18n/nl.po
  mail_template_multi_company/models/__init__.py
  mail_template_multi_company/models/mail_template.py
  mail_template_multi_company/readme/CONFIGURE.rst
  mail_template_multi_company/readme/CONTRIBUTORS.rst
  mail_template_multi_company/readme/DESCRIPTION.rst
  mail_template_multi_company/readme/USAGE.rst
  mail_template_multi_company/security/mail_template.xml
  mail_template_multi_company/static/description/icon.png
  mail_template_multi_company/static/description/index.html
  mail_template_multi_company/views/mail_template.xml
  setup/mail_template_multi_company/odoo/addons/mail_template_multi_company
  setup/mail_template_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#403 [15.0][MIG] mail_multicompany
  mail_multicompany/README.rst
  mail_multicompany/__init__.py
  mail_multicompany/__manifest__.py
  mail_multicompany/i18n/es.po
  mail_multicompany/i18n/mail_multicompany.pot
  mail_multicompany/models/__init__.py
  mail_multicompany/models/ir_mail_server.py
  mail_multicompany/models/mail_message.py
  mail_multicompany/readme/CONFIGURE.rst
  mail_multicompany/readme/CONTRIBUTORS.rst
  mail_multicompany/readme/DESCRIPTION.rst
  mail_multicompany/readme/USAGE.rst
  mail_multicompany/security/mail_security.xml
  mail_multicompany/static/description/icon.png
  mail_multicompany/static/description/index.html
  mail_multicompany/tests/__init__.py
  mail_multicompany/tests/test_mail_multicompany.py
  mail_multicompany/views/ir_mail_server_view.xml
  setup/mail_multicompany/odoo/addons/mail_multicompany
  setup/mail_multicompany/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#389 [16.0][MIG] res_company_active (from 12.0 to 16.0)
  res_company_active/README.rst
  res_company_active/__init__.py
  res_company_active/__manifest__.py
  res_company_active/demo/res_company.xml
  res_company_active/demo/res_groups.xml
  res_company_active/i18n/fr.po
  res_company_active/i18n/hr.po
  res_company_active/i18n/res_company_active.pot
  res_company_active/models/__init__.py
  res_company_active/models/res_company.py
  res_company_active/readme/CONTRIBUTORS.rst
  res_company_active/readme/DESCRIPTION.rst
  res_company_active/static/description/icon.png
  res_company_active/static/description/index.html
  res_company_active/static/description/res_company_form.png
  res_company_active/static/description/validation_error.png
  res_company_active/tests/__init__.py
  res_company_active/tests/test_module.py
  res_company_active/views/view_res_company.xml
  setup/res_company_active/odoo/addons/res_company_active
  setup/res_company_active/setup.py
Labels: approved, bot is merging ⏳

#503 [15.0][FIX] base_multi_company: allow reinstalling submodules
  .oca/oca-port/blacklist/base_multi_company.json
  base_multi_company/hooks.py
Labels: bot is merging ⏳
