Repository OCA/multi-company, pull requests merged in 2023-12, with the labels that each got.

#536 [15.0][FIX] base_multi_company: Proper _check_company when multiple companies selected
  base_multi_company/models/__init__.py
  base_multi_company/models/base.py
  base_multi_company/models/multi_company_abstract.py
Labels: approved, bot is merging ⏳

#539 [14.0][FIX] base_multi_company: _check_company multi-record aware
  base_multi_company/models/base.py
Labels: approved, bot is merging ⏳

#458 [16.0][MIG] base_multi_company
  base_multi_company/README.rst
  base_multi_company/__init__.py
  base_multi_company/__manifest__.py
  base_multi_company/hooks.py
  base_multi_company/i18n/base_multi_company.pot
  base_multi_company/i18n/es.po
  base_multi_company/i18n/es_AR.po
  base_multi_company/i18n/fr.po
  base_multi_company/i18n/hr.po
  base_multi_company/i18n/nl_NL.po
  base_multi_company/i18n/pt.po
  base_multi_company/i18n/pt_BR.po
  base_multi_company/i18n/zh_CN.po
  base_multi_company/models/__init__.py
  base_multi_company/models/base.py
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/readme/CONTRIBUTORS.rst
  base_multi_company/readme/DESCRIPTION.rst
  base_multi_company/readme/DEVELOPER.rst
  base_multi_company/static/description/icon.png
  base_multi_company/static/description/index.html
  base_multi_company/tests/__init__.py
  base_multi_company/tests/multi_company_abstract_tester.py
  base_multi_company/tests/test_multi_company_abstract.py
  setup/base_multi_company/odoo/addons/base_multi_company
  setup/base_multi_company/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#538 [14.0] [FIX] base_multi_company: apply '_name_search' fix to 'search_read'
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
Labels: approved, bot is merging ⏳

#543 [15.0][FW][FIX] base_multi_company: apply '_name_search' fix to 'search_read'
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
Labels: bot is merging ⏳

#544 [16.0][FW][FIX] base_multi_company: apply '_name_search' fix to 'search_read'
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
Labels: bot is merging ⏳

#541 [FIX]purchase_sale_inter_company: handle pickings with lots/serials
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/__manifest__.py
  purchase_sale_inter_company/models/res_company.py
  purchase_sale_inter_company/models/res_config.py
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/readme/CONTRIBUTORS.rst
  purchase_sale_inter_company/readme/DESCRIPTION.rst
  purchase_sale_inter_company/static/description/index.html
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, bot is merging ⏳

#542 [FIX] purchase_sale_inter_company: sync moves with same product
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, bot is merging ⏳

#523 purchase_sale_inter_company: fix validation of several picking. self can have more than one record
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, ready to merge, bot is merging ⏳

#548 [14.0][FIX]base_multi_company fix singleton File "/opt/odoo/parts/OCA/mul…
  base_multi_company/models/base.py
Labels: bot is merging ⏳

#500 [15.0][FIX] account_invoice_inter_company: context can cause a UserError
  account_invoice_inter_company/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#515 [16.0][ADD] account_reconcile_model_multicompany_propagate
  account_reconcile_model_multicompany_propagate/README.rst
  account_reconcile_model_multicompany_propagate/__init__.py
  account_reconcile_model_multicompany_propagate/__manifest__.py
  account_reconcile_model_multicompany_propagate/i18n/account_reconcile_model_multicompany_propagate.pot
  account_reconcile_model_multicompany_propagate/i18n/es.po
  account_reconcile_model_multicompany_propagate/models/__init__.py
  account_reconcile_model_multicompany_propagate/models/account_reconcile_model.py
  account_reconcile_model_multicompany_propagate/readme/CONFIGURE.rst
  account_reconcile_model_multicompany_propagate/readme/CONTRIBUTORS.rst
  account_reconcile_model_multicompany_propagate/readme/DESCRIPTION.rst
  account_reconcile_model_multicompany_propagate/readme/USAGE.rst
  account_reconcile_model_multicompany_propagate/static/description/icon.png
  account_reconcile_model_multicompany_propagate/tests/__init__.py
  account_reconcile_model_multicompany_propagate/tests/test_reconcile_model.py
  account_reconcile_model_multicompany_propagate/views/account_reconcile_model.xml
  setup/account_reconcile_model_multicompany_propagate/odoo/addons/account_reconcile_model_multicompany_propagate
  setup/account_reconcile_model_multicompany_propagate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#493 [MIG] stock_intercompany: Migration to 16.0
  setup/stock_intercompany/odoo/addons/stock_intercompany
  setup/stock_intercompany/setup.py
  stock_intercompany/README.rst
  stock_intercompany/__init__.py
  stock_intercompany/__manifest__.py
  stock_intercompany/i18n/stock_intercompany.pot
  stock_intercompany/models/__init__.py
  stock_intercompany/models/res_company.py
  stock_intercompany/models/res_config_settings.py
  stock_intercompany/models/stock_move.py
  stock_intercompany/models/stock_move_line.py
  stock_intercompany/models/stock_picking.py
  stock_intercompany/readme/CONFIGURE.rst
  stock_intercompany/readme/CONTRIBUTORS.rst
  stock_intercompany/readme/DESCRIPTION.rst
  stock_intercompany/static/description/icon.png
  stock_intercompany/static/description/index.html
  stock_intercompany/tests/__init__.py
  stock_intercompany/tests/test_intercompany_picking.py
  stock_intercompany/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#482 [12.0][BKP] Backport from 14.0 to 12.0 for mail_multicompany
  mail_multicompany/README.rst
  mail_multicompany/__init__.py
  mail_multicompany/__manifest__.py
  mail_multicompany/i18n/es.po
  mail_multicompany/i18n/mail_multicompany.pot
  mail_multicompany/models/__init__.py
  mail_multicompany/models/ir_mail_server.py
  mail_multicompany/models/mail_message.py
  mail_multicompany/readme/CONFIGURE.rst
  mail_multicompany/readme/CONTRIBUTORS.rst
  mail_multicompany/readme/DESCRIPTION.rst
  mail_multicompany/readme/USAGE.rst
  mail_multicompany/security/mail_security.xml
  mail_multicompany/static/description/icon.png
  mail_multicompany/static/description/index.html
  mail_multicompany/tests/__init__.py
  mail_multicompany/tests/test_mail_multicompany.py
  mail_multicompany/views/ir_mail_server_view.xml
  setup/mail_multicompany/odoo/addons/mail_multicompany
  setup/mail_multicompany/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#495 [15.0][MIG] res_company_code
  res_company_code/README.rst
  res_company_code/__init__.py
  res_company_code/__manifest__.py
  res_company_code/demo/res_company.xml
  res_company_code/demo/res_groups.xml
  res_company_code/i18n/es.po
  res_company_code/i18n/fr.po
  res_company_code/i18n/res_company_code.pot
  res_company_code/models/__init__.py
  res_company_code/models/ir_http.py
  res_company_code/models/res_company.py
  res_company_code/readme/CONTRIBUTORS.rst
  res_company_code/readme/DESCRIPTION.rst
  res_company_code/static/description/icon.png
  res_company_code/static/description/index.html
  res_company_code/static/description/res_company_form.png
  res_company_code/static/description/res_company_tree.png
  res_company_code/static/description/switch_company_menu.png
  res_company_code/tests/__init__.py
  res_company_code/tests/test_res_company_code.py
  res_company_code/views/view_res_company.xml
  setup/res_company_code/odoo/addons/res_company_code
  setup/res_company_code/setup.py
Labels: bot is merging ⏳, stale

#392 [16.0][MIG] res_company_category (from 12.0 to 16.0)
  res_company_category/README.rst
  res_company_category/__init__.py
  res_company_category/__manifest__.py
  res_company_category/demo/res_company.xml
  res_company_category/demo/res_company_category.xml
  res_company_category/demo/res_groups.xml
  res_company_category/i18n/fr.po
  res_company_category/i18n/res_company_category.pot
  res_company_category/models/__init__.py
  res_company_category/models/res_company.py
  res_company_category/models/res_company_category.py
  res_company_category/readme/CONFIGURE.rst
  res_company_category/readme/CONTRIBUTORS.rst
  res_company_category/readme/DESCRIPTION.rst
  res_company_category/security/ir.model.access.csv
  res_company_category/static/description/icon.png
  res_company_category/static/description/index.html
  res_company_category/static/description/res_company_category_form.png
  res_company_category/static/description/res_company_category_tree.png
  res_company_category/static/description/res_company_form.png
  res_company_category/views/view_res_company.xml
  res_company_category/views/view_res_company_category.xml
  setup/res_company_category/odoo/addons/res_company_category
  setup/res_company_category/setup.py
Labels: bot is merging ⏳

#475 [16.0] [MIG] res_company_code
  res_company_code/README.rst
  res_company_code/__init__.py
  res_company_code/__manifest__.py
  res_company_code/demo/res_company.xml
  res_company_code/demo/res_groups.xml
  res_company_code/i18n/es.po
  res_company_code/i18n/fr.po
  res_company_code/i18n/res_company_code.pot
  res_company_code/models/__init__.py
  res_company_code/models/ir_http.py
  res_company_code/models/res_company.py
  res_company_code/readme/CONTRIBUTORS.rst
  res_company_code/readme/DESCRIPTION.rst
  res_company_code/static/description/icon.png
  res_company_code/static/description/index.html
  res_company_code/static/description/res_company_form.png
  res_company_code/static/description/res_company_tree.png
  res_company_code/static/description/switch_company_menu.png
  res_company_code/tests/__init__.py
  res_company_code/tests/test_res_company_code.py
  res_company_code/views/view_res_company.xml
  setup/res_company_code/odoo/addons/res_company_code
  setup/res_company_code/setup.py
Labels: bot is merging ⏳

#506 [MIG] calendar_event_multi_company: Migration to 15.0
  calendar_event_multi_company/README.rst
  calendar_event_multi_company/__init__.py
  calendar_event_multi_company/__manifest__.py
  calendar_event_multi_company/i18n/calendar_event_multi_company.pot
  calendar_event_multi_company/i18n/it.po
  calendar_event_multi_company/models/__init__.py
  calendar_event_multi_company/models/calendar_event.py
  calendar_event_multi_company/readme/CONTRIBUTORS.rst
  calendar_event_multi_company/readme/DESCRIPTION.rst
  calendar_event_multi_company/security/calendar_event.xml
  calendar_event_multi_company/static/description/icon.png
  calendar_event_multi_company/static/description/index.html
  calendar_event_multi_company/views/calendar_event.xml
  setup/calendar_event_multi_company/odoo/addons/calendar_event_multi_company
  setup/calendar_event_multi_company/setup.py
Labels: bot is merging ⏳

#550 [REF] Bump copier answer from version 1.17 to 1.20.
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
Labels: bot is merging ⏳

#460 [16.0][MIG] partner_multi_company
  partner_multi_company/README.rst
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/i18n/de.po
  partner_multi_company/i18n/es.po
  partner_multi_company/i18n/fr.po
  partner_multi_company/i18n/hr.po
  partner_multi_company/i18n/partner_multi_company.pot
  partner_multi_company/i18n/pt.po
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/models/res_users.py
  partner_multi_company/readme/CONTRIBUTORS.rst
  partner_multi_company/readme/DESCRIPTION.rst
  partner_multi_company/readme/INSTALL.rst
  partner_multi_company/readme/ROADMAP.rst
  partner_multi_company/readme/USAGE.rst
  partner_multi_company/static/description/icon.png
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/__init__.py
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_partner_view.xml
  setup/partner_multi_company/odoo/addons/partner_multi_company
  setup/partner_multi_company/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#551 [16.0][FIX] base_multi_company: Check multiple companies
  base_multi_company/models/base.py
Labels: bot is merging ⏳

#552 [FIX] base_multi_company: Check multiple companies
  base_multi_company/models/base.py
Labels: bot is merging ⏳

#553 [15.0][FIX] base_multi_company: Check multiple companies
  base_multi_company/models/base.py
Labels: bot is merging ⏳

#555 [14.0][FIX] purchase_sale_inter_company: fix demo data
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/__manifest__.py
  purchase_sale_inter_company/demo/res_partner_demo.xml
  purchase_sale_inter_company/static/description/index.html
Labels: bot is merging ⏳

#487 [16.0][MIG] purchase_sale_stock_inter_company: Migration to 16.0
  purchase_sale_stock_inter_company/README.rst
  purchase_sale_stock_inter_company/__init__.py
  purchase_sale_stock_inter_company/__manifest__.py
  purchase_sale_stock_inter_company/i18n/de.po
  purchase_sale_stock_inter_company/i18n/es.po
  purchase_sale_stock_inter_company/i18n/fr.po
  purchase_sale_stock_inter_company/i18n/fr_FR.po
  purchase_sale_stock_inter_company/i18n/it.po
  purchase_sale_stock_inter_company/i18n/purchase_sale_stock_inter_company.pot
  purchase_sale_stock_inter_company/i18n/sl.po
  purchase_sale_stock_inter_company/i18n/zh_CN.po
  purchase_sale_stock_inter_company/models/__init__.py
  purchase_sale_stock_inter_company/models/purchase_order.py
  purchase_sale_stock_inter_company/models/res_company.py
  purchase_sale_stock_inter_company/models/res_config.py
  purchase_sale_stock_inter_company/models/stock_picking.py
  purchase_sale_stock_inter_company/readme/CONFIGURE.rst
  purchase_sale_stock_inter_company/readme/CONTRIBUTORS.rst
  purchase_sale_stock_inter_company/readme/DESCRIPTION.rst
  purchase_sale_stock_inter_company/static/description/icon.png
  purchase_sale_stock_inter_company/static/description/index.html
  purchase_sale_stock_inter_company/tests/__init__.py
  purchase_sale_stock_inter_company/tests/test_inter_company_purchase_sale_stock.py
  purchase_sale_stock_inter_company/views/res_config_view.xml
  setup/purchase_sale_stock_inter_company/odoo/addons/purchase_sale_stock_inter_company
  setup/purchase_sale_stock_inter_company/setup.py
Labels: approved, bot is merging ⏳

#560 [14.0] [IMP] purchase_sale_inter_company: manage and sync state
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: bot is merging ⏳

#559 [14.0][FIX] purchase_sale_inter_company: sync confirmed unlocked purchase updates
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/models/purchase_order.py
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/readme/ROADMAP.rst
  purchase_sale_inter_company/static/description/index.html
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, bot is merging ⏳
