Repository OCA/multi-company, pull requests merged in 2024-10, with the labels that each got.

#707 [14.0][FIX] purchase_sale_inter_company: fix no attribute 'company_id'
  purchase_sale_inter_company/models/stock_picking.py
Labels: approved

#702 [ADD] project_multi_company module
  project_multi_company/README.rst
  project_multi_company/__init__.py
  project_multi_company/__manifest__.py
  project_multi_company/i18n/fr.po
  project_multi_company/models/__init__.py
  project_multi_company/models/project_tags.py
  project_multi_company/models/project_task_type.py
  project_multi_company/readme/CONTRIBUTORS.rst
  project_multi_company/readme/DESCRIPTION.rst
  project_multi_company/security/ir_rule.xml
  project_multi_company/views/view_project_tags.xml
  project_multi_company/views/view_project_task_type.xml
  setup/project_multi_company/odoo/addons/project_multi_company
  setup/project_multi_company/setup.py
Labels: bot is merging ⏳

#626 [17.0] [MIG] partner_multi_company: Migration to 17.0
  mail_multicompany/tests/test_mail_multicompany.py
  partner_multi_company/README.rst
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/i18n/de.po
  partner_multi_company/i18n/es.po
  partner_multi_company/i18n/fr.po
  partner_multi_company/i18n/hr.po
  partner_multi_company/i18n/it.po
  partner_multi_company/i18n/partner_multi_company.pot
  partner_multi_company/i18n/pt.po
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/models/res_users.py
  partner_multi_company/pyproject.toml
  partner_multi_company/readme/CONTRIBUTORS.md
  partner_multi_company/readme/DESCRIPTION.md
  partner_multi_company/readme/INSTALL.md
  partner_multi_company/readme/ROADMAP.md
  partner_multi_company/readme/USAGE.md
  partner_multi_company/static/description/icon.png
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/__init__.py
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
