Repository OCA/multi-company, pull requests merged in 2024-06, with the labels that each got.

#631 [16.0][IMP] account_invoice_inter_company: add setting to disable or enable intercompany invoicing
  account_invoice_inter_company/README.rst
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/models/res_company.py
  account_invoice_inter_company/models/res_config_settings.py
  account_invoice_inter_company/readme/CONFIGURE.rst
  account_invoice_inter_company/static/description/index.html
  account_invoice_inter_company/tests/test_inter_company_invoice.py
  account_invoice_inter_company/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#537 [16.0][MIG] pos_restaurant_multi_company
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
  pos_restaurant_multi_company/README.rst
  pos_restaurant_multi_company/__init__.py
  pos_restaurant_multi_company/__manifest__.py
  pos_restaurant_multi_company/hooks.py
  pos_restaurant_multi_company/i18n/fr.po
  pos_restaurant_multi_company/i18n/pos_restaurant_multi_company.pot
  pos_restaurant_multi_company/models/__init__.py
  pos_restaurant_multi_company/models/restaurant_floor.py
  pos_restaurant_multi_company/models/restaurant_printer.py
  pos_restaurant_multi_company/models/restaurant_table.py
  pos_restaurant_multi_company/readme/CONTRIBUTORS.rst
  pos_restaurant_multi_company/readme/DESCRIPTION.rst
  pos_restaurant_multi_company/security/ir_rule.xml
  pos_restaurant_multi_company/static/description/icon.png
  pos_restaurant_multi_company/static/description/index.html
  pos_restaurant_multi_company/views/restaurant_floor.xml
  pos_restaurant_multi_company/views/restaurant_printer.xml
  setup/pos_restaurant_multi_company/odoo/addons/pos_restaurant_multi_company
  setup/pos_restaurant_multi_company/setup.py
Labels: bot is merging ⏳, stale

#615 [16.0][ADD] partner_account_multicompany_default
  partner_account_multicompany_default/README.rst
  partner_account_multicompany_default/__init__.py
  partner_account_multicompany_default/__manifest__.py
  partner_account_multicompany_default/models/__init__.py
  partner_account_multicompany_default/models/partner.py
  partner_account_multicompany_default/readme/CONFIGURE.rst
  partner_account_multicompany_default/readme/CONTRIBUTORS.rst
  partner_account_multicompany_default/readme/DESCRIPTION.rst
  partner_account_multicompany_default/readme/ROADMAP.rst
  partner_account_multicompany_default/readme/USAGE.rst
  partner_account_multicompany_default/static/description/icon.png
  partner_account_multicompany_default/static/description/index.html
  partner_account_multicompany_default/tests/__init__.py
  partner_account_multicompany_default/tests/test_partner.py
  partner_account_multicompany_default/views/partner_view.xml
  setup/partner_account_multicompany_default/odoo/addons/partner_account_multicompany_default
  setup/partner_account_multicompany_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#637 [14.0][FIX] Picking sync should also work for dropshipping
  purchase_sale_inter_company/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#646 [14.0][FIX] purchase_stock_inter_company: support 'no backorder' case
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, bot is merging ⏳

#614 [15.0][MIG] login_all_company: Migration to 15.0
  login_all_company/README.rst
  login_all_company/__init__.py
  login_all_company/__manifest__.py
  login_all_company/i18n/login_all_company.pot
  login_all_company/readme/CONTRIBUTORS.rst
  login_all_company/readme/DESCRIPTION.rst
  login_all_company/static/description/icon.png
  login_all_company/static/description/index.html
  login_all_company/static/src/js/company_service.esm.js
  setup/login_all_company/odoo/addons/login_all_company
  setup/login_all_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳
