Repository OCA/multi-company, pull requests merged in 2024-05, with the labels that each got.

#570 intercompany_shared_contact: fix wrong field computation and add test
  intercompany_shared_contact/__manifest__.py
  intercompany_shared_contact/models/res_partner.py
  intercompany_shared_contact/tests/test_shared_contacts.py
Labels: bot is merging ⏳

#612 [16.0][IMP] mail_multicompany: search most appropriate server based on the from email
  mail_multicompany/models/mail_message.py
  mail_multicompany/tests/test_mail_multicompany.py
Labels: bot is merging ⏳

#617 [FIX] account_reconcile_model_multicompany_propagate: compute in batch
  account_reconcile_model_multicompany_propagate/models/account_reconcile_model.py
  account_reconcile_model_multicompany_propagate/tests/test_reconcile_model.py
Labels: approved, bot is merging ⏳

#576 [17.0][MIG] mail_multicompany
  mail_multicompany/README.rst
  mail_multicompany/__init__.py
  mail_multicompany/__manifest__.py
  mail_multicompany/i18n/es.po
  mail_multicompany/i18n/mail_multicompany.pot
  mail_multicompany/migrations/17.0.1.0.0/pre-migration.py
  mail_multicompany/models/__init__.py
  mail_multicompany/models/ir_mail_server.py
  mail_multicompany/models/mail_message.py
  mail_multicompany/pyproject.toml
  mail_multicompany/readme/CONFIGURE.md
  mail_multicompany/readme/CONTRIBUTORS.md
  mail_multicompany/readme/DESCRIPTION.md
  mail_multicompany/readme/USAGE.md
  mail_multicompany/security/mail_security.xml
  mail_multicompany/static/description/icon.png
  mail_multicompany/static/description/index.html
  mail_multicompany/tests/__init__.py
  mail_multicompany/tests/test_mail_multicompany.py
  mail_multicompany/views/ir_mail_server_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#562 [16.0][ADD] stock_intercompany_bidirectional
  setup/stock_intercompany_bidirectional/odoo/addons/stock_intercompany_bidirectional
  setup/stock_intercompany_bidirectional/setup.py
  stock_intercompany_bidirectional/README.rst
  stock_intercompany_bidirectional/__init__.py
  stock_intercompany_bidirectional/__manifest__.py
  stock_intercompany_bidirectional/data/demo_data.xml
  stock_intercompany_bidirectional/models/__init__.py
  stock_intercompany_bidirectional/models/res_company.py
  stock_intercompany_bidirectional/models/res_config_settings.py
  stock_intercompany_bidirectional/models/stock_picking.py
  stock_intercompany_bidirectional/readme/CONFIGURE.rst
  stock_intercompany_bidirectional/readme/CONTEXT.rst
  stock_intercompany_bidirectional/readme/CONTRIBUTORS.rst
  stock_intercompany_bidirectional/readme/DESCRIPTION.rst
  stock_intercompany_bidirectional/readme/USAGE.rst
  stock_intercompany_bidirectional/static/description/icon.png
  stock_intercompany_bidirectional/static/description/icon.svg
  stock_intercompany_bidirectional/static/description/index.html
  stock_intercompany_bidirectional/tests/__init__.py
  stock_intercompany_bidirectional/tests/test_intercompany_bidirectional_picking.py
  stock_intercompany_bidirectional/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#518 [MIG] utm_source_multi_company: Migration to 15.0
  setup/utm_source_multi_company/odoo/addons/utm_source_multi_company
  setup/utm_source_multi_company/setup.py
  utm_source_multi_company/README.rst
  utm_source_multi_company/__init__.py
  utm_source_multi_company/__manifest__.py
  utm_source_multi_company/i18n/utm_source_multi_company.pot
  utm_source_multi_company/models/__init__.py
  utm_source_multi_company/models/utm_source.py
  utm_source_multi_company/readme/CONTRIBUTORS.rst
  utm_source_multi_company/readme/DESCRIPTION.rst
  utm_source_multi_company/security/utm_source.xml
  utm_source_multi_company/static/description/icon.png
  utm_source_multi_company/static/description/index.html
  utm_source_multi_company/views/utm_source.xml
Labels: approved, bot is merging ⏳

#622 [14.0] [ADD] partner_multi_company_pos
  partner_multi_company_pos/README.rst
  partner_multi_company_pos/__init__.py
  partner_multi_company_pos/__manifest__.py
  partner_multi_company_pos/models/__init__.py
  partner_multi_company_pos/models/res_partner.py
  partner_multi_company_pos/readme/CONTRIBUTORS.rst
  partner_multi_company_pos/readme/DESCRIPTION.rst
  partner_multi_company_pos/static/description/index.html
  setup/partner_multi_company_pos/odoo/addons/partner_multi_company_pos
  setup/partner_multi_company_pos/setup.py
Labels: approved, bot is merging ⏳

#629 [16.0][IMP-FIX] sale_product_company: define table in m2m model
  sale_product_company/__manifest__.py
  sale_product_company/migrations/16.0.2.0.0/pre-migration.py
  sale_product_company/models/product_template.py
Labels: approved, bot is merging ⏳

#628 [16.0][MIG] product_multi_company: Migration to version 16.0
  product_multi_company/README.rst
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/i18n/es.po
  product_multi_company/i18n/fr.po
  product_multi_company/i18n/hr.po
  product_multi_company/i18n/nl_NL.po
  product_multi_company/i18n/product_multi_company.pot
  product_multi_company/i18n/pt.po
  product_multi_company/models/__init__.py
  product_multi_company/models/product_product.py
  product_multi_company/models/product_template.py
  product_multi_company/readme/CONTRIBUTORS.rst
  product_multi_company/readme/DESCRIPTION.rst
  product_multi_company/readme/INSTALL.rst
  product_multi_company/readme/USAGE.rst
  product_multi_company/static/description/icon.png
  product_multi_company/static/description/index.html
  product_multi_company/tests/__init__.py
  product_multi_company/tests/common.py
  product_multi_company/tests/test_product_multi_company.py
  product_multi_company/views/product_template_view.xml
  setup/product_multi_company/odoo/addons/product_multi_company
  setup/product_multi_company/setup.py
Labels: approved, bot is merging ⏳
