Repository OCA/multi-company, pull requests merged in 2024-02, with the labels that each got.

#575 [14.0][FIX] partner_multi_company: default value for res_partner.company_ids
  partner_multi_company/README.rst
  partner_multi_company/__manifest__.py
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_company.py
  partner_multi_company/models/res_config_settings.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/readme/USAGE.rst
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#583 [14.0] [FIX] purchase_sale_inter_company: wrong field
  purchase_sale_inter_company/models/sale_order.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, bot is merging ⏳

#574 [14.0] ir_config_parameter_multi_company
  ir_config_parameter_multi_company/README.rst
  ir_config_parameter_multi_company/__init__.py
  ir_config_parameter_multi_company/__manifest__.py
  ir_config_parameter_multi_company/models/__init__.py
  ir_config_parameter_multi_company/models/ir_config_parameter.py
  ir_config_parameter_multi_company/readme/CONTRIBUTORS.rst
  ir_config_parameter_multi_company/readme/DESCRIPTION.rst
  ir_config_parameter_multi_company/security/parameter_security.xml
  ir_config_parameter_multi_company/static/description/index.html
  ir_config_parameter_multi_company/tests/__init__.py
  ir_config_parameter_multi_company/tests/test_ir_config_parameter_multi_company.py
  ir_config_parameter_multi_company/views/ir_config_parameter_view.xml
  setup/ir_config_parameter_multi_company/odoo/addons/ir_config_parameter_multi_company
  setup/ir_config_parameter_multi_company/setup.py
Labels: bot is merging ⏳

#590 [14.0][FIX] product_multi_company: recompute variant companies
  product_multi_company/README.rst
  product_multi_company/models/__init__.py
  product_multi_company/models/product.py
  product_multi_company/readme/CONTRIBUTORS.rst
  product_multi_company/static/description/index.html
  product_multi_company/tests/test_product_multi_company.py
Labels: approved, bot is merging ⏳
