Repository OCA/multi-company, pull requests merged in 2024-11, with the labels that each got.

#717 [16.0][FIX] base_multi_company: search with in operator
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
  purchase_sale_container_deposit_inter_company/tests/test_inter_company_purchase_sale_container_deposit.py
Labels: approved, bot is merging ⏳

#716 [15.0][FIX] product_multi_company: search in False
  product_multi_company/models/__init__.py
  product_multi_company/models/product_product.py
  product_multi_company/static/description/index.html
  product_multi_company/tests/test_product_multi_company.py
Labels: approved, bot is merging ⏳

#719 [17.0][FIX] base_multi_company: search with in operator
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/tests/test_multi_company_abstract.py
Labels: approved, bot is merging ⏳

#720 [16.0][FIX] product_multi_company: search in False
  product_multi_company/models/product_product.py
  product_multi_company/static/description/index.html
  product_multi_company/tests/test_product_multi_company.py
Labels: approved, bot is merging ⏳

#625 [17.0] [MIG] product_multi_company: Migration to 17.0
  product_multi_company/README.rst
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/i18n/es.po
  product_multi_company/i18n/fr.po
  product_multi_company/i18n/hr.po
  product_multi_company/i18n/it.po
  product_multi_company/i18n/nl_NL.po
  product_multi_company/i18n/product_multi_company.pot
  product_multi_company/i18n/pt.po
  product_multi_company/models/__init__.py
  product_multi_company/models/product_product.py
  product_multi_company/models/product_template.py
  product_multi_company/pyproject.toml
  product_multi_company/readme/CONTRIBUTORS.md
  product_multi_company/readme/DESCRIPTION.md
  product_multi_company/readme/INSTALL.md
  product_multi_company/readme/USAGE.md
  product_multi_company/static/description/icon.png
  product_multi_company/static/description/index.html
  product_multi_company/tests/__init__.py
  product_multi_company/tests/common.py
  product_multi_company/tests/test_product_multi_company.py
  product_multi_company/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#721 [13.0][IMP] purchase_sale_inter_company: return created SO
  purchase_sale_inter_company/models/purchase_order.py
Labels: approved, bot is merging ⏳

#724 [16.0][FW][IMP] purchase_sale_inter_company: return created SO
  purchase_sale_inter_company/models/purchase_order.py
Labels: approved, bot is merging ⏳

#723 [15.0][FW][IMP] purchase_sale_inter_company: return created SO
  purchase_sale_inter_company/models/purchase_order.py
Labels: approved, bot is merging ⏳

#725 [12.0][BK][IMP] purchase_sale_inter_company: return created SO
  purchase_sale_inter_company/models/purchase_order.py
Labels: approved, bot is merging ⏳

#645 [15.0][ADD] product_category_multi_company
  product_category_multi_company/README.rst
  product_category_multi_company/__init__.py
  product_category_multi_company/__manifest__.py
  product_category_multi_company/models/__init__.py
  product_category_multi_company/models/product_category.py
  product_category_multi_company/models/product_template.py
  product_category_multi_company/readme/CONTRIBUTORS.rst
  product_category_multi_company/readme/DESCRIPTION.rst
  product_category_multi_company/readme/USAGE.rst
  product_category_multi_company/static/description/index.html
  product_category_multi_company/tests/__init__.py
  product_category_multi_company/tests/test_product_category_multi_company.py
  product_category_multi_company/views/product_category.xml
  setup/product_category_multi_company/odoo/addons/product_category_multi_company
  setup/product_category_multi_company/setup.py
Labels: approved, bot is merging ⏳, stale

#727 [13.0][IMP] account_invoice_inter_company: propagate invoice payment reference
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳

#731 [17.0][FW][IMP] account_invoice_inter_company: propagate invoice payment reference
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: bot is merging ⏳

#728 [14.0][FW][IMP] account_invoice_inter_company: propagate invoice payment reference
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: bot is merging ⏳

#730 [16.0][FW][IMP] account_invoice_inter_company: propagate invoice payment reference
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: bot is merging ⏳

#650 [16.0][IMP] product_account_multicompany_default propagate product category accounts
  product_account_multicompany_default/README.rst
  product_account_multicompany_default/__manifest__.py
  product_account_multicompany_default/models/__init__.py
  product_account_multicompany_default/models/product_category.py
  product_account_multicompany_default/readme/CONTRIBUTORS.rst
  product_account_multicompany_default/readme/DESCRIPTION.rst
  product_account_multicompany_default/static/description/index.html
  product_account_multicompany_default/tests/__init__.py
  product_account_multicompany_default/tests/test_product_category.py
  product_account_multicompany_default/views/product_category_view.xml
Labels: approved, ready to merge, bot is merging ⏳, stale
