Repository OCA/multi-company, pull requests merged in 2024-12, with the labels that each got.

#658 [16.0][MIG] account_move_change_company: Migration to 16.0
  account_move_change_company/README.rst
  account_move_change_company/__init__.py
  account_move_change_company/__manifest__.py
  account_move_change_company/i18n/account_move_change_company.pot
  account_move_change_company/i18n/es.po
  account_move_change_company/models/__init__.py
  account_move_change_company/models/account_move.py
  account_move_change_company/readme/CONTRIBUTORS.rst
  account_move_change_company/readme/DESCRIPTION.rst
  account_move_change_company/static/description/icon.png
  account_move_change_company/static/description/index.html
  account_move_change_company/tests/__init__.py
  account_move_change_company/tests/test_change_company.py
  account_move_change_company/views/account_move.xml
  setup/account_move_change_company/odoo/addons/account_move_change_company
  setup/account_move_change_company/setup.py
Labels: bot is merging ⏳, stale

#733 [13.0][FIX] purchase_sale_stock_inter_company: Allow reception with serial tracking and partial quantity (Dropshipping)
  purchase_sale_stock_inter_company/models/__init__.py
  purchase_sale_stock_inter_company/models/stock_move_line.py
  purchase_sale_stock_inter_company/models/stock_picking.py
  purchase_sale_stock_inter_company/tests/test_inter_company_purchase_sale_stock.py
Labels: approved, ready to merge, bot is merging ⏳

#750 [16.0][FIX] account_invoice_inter_company: Add group multicurrency to avoid error in tests
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved
