Repository OCA/multi-company, pull requests merged in 2025-02, with the labels that each got.

#485 [14.0][FIX] mail_template_multi_company: Don't set default company on mail template
  mail_template_multi_company/models/mail_template.py
Labels: approved, bot is merging ⏳, stale

#766 [16.0][port][account_invoice_inter_company] attach pdf
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳

#769 [17.0][IMP] account_invoice_inter_company: Add pdf invoices in both companies
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳

#760 [16.0][FIX] base_multi_company: support `in False` search operators
  base_multi_company/README.rst
  base_multi_company/hooks.py
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/readme/CONTRIBUTORS.rst
  base_multi_company/readme/DEVELOPER.rst
  base_multi_company/static/description/index.html
  base_multi_company/tests/test_multi_company_abstract.py
Labels: approved, bot is merging ⏳

#761 [16.0][FIX] partner_multi_company: remove unnecessary rule rewrite hooks
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/migrations/16.0.1.1.1/post-migration.py
  partner_multi_company/tests/test_partner_multi_company.py
Labels: approved, ready to merge, bot is merging ⏳

#763 [FIX] ir_config_parameter_multi_company: hook to avoid error with CRM
  ir_config_parameter_multi_company/__init__.py
  ir_config_parameter_multi_company/__manifest__.py
  ir_config_parameter_multi_company/hooks.py
Labels: bot is merging ⏳

#767 [16.0][MIG] crm_tag_multi_company
  crm_tag_multi_company/README.rst
  crm_tag_multi_company/__init__.py
  crm_tag_multi_company/__manifest__.py
  crm_tag_multi_company/i18n/crm_tag_multi_company.pot
  crm_tag_multi_company/models/__init__.py
  crm_tag_multi_company/models/crm_lead.py
  crm_tag_multi_company/models/crm_tag.py
  crm_tag_multi_company/readme/CONTRIBUTORS.rst
  crm_tag_multi_company/readme/DESCRIPTION.rst
  crm_tag_multi_company/security/crm_tag.xml
  crm_tag_multi_company/static/description/icon.png
  crm_tag_multi_company/static/description/index.html
  crm_tag_multi_company/views/crm_tag.xml
  crm_tag_multi_company_event_crm/README.rst
  crm_tag_multi_company_event_crm/__init__.py
  crm_tag_multi_company_event_crm/__manifest__.py
  crm_tag_multi_company_event_crm/models/__init__.py
  crm_tag_multi_company_event_crm/models/event_lead_rule.py
  crm_tag_multi_company_event_crm/readme/CONTRIBUTORS.rst
  crm_tag_multi_company_event_crm/readme/DESCRIPTION.rst
  crm_tag_multi_company_event_crm/static/description/index.html
  crm_tag_multi_company_sale/README.rst
  crm_tag_multi_company_sale/__init__.py
  crm_tag_multi_company_sale/__manifest__.py
  crm_tag_multi_company_sale/models/__init__.py
  crm_tag_multi_company_sale/models/sale_order.py
  crm_tag_multi_company_sale/readme/CONTRIBUTORS.rst
  crm_tag_multi_company_sale/readme/DESCRIPTION.rst
  crm_tag_multi_company_sale/static/description/index.html
  setup/crm_tag_multi_company/odoo/addons/crm_tag_multi_company
  setup/crm_tag_multi_company/setup.py
  setup/crm_tag_multi_company_event_crm/odoo/addons/crm_tag_multi_company_event_crm
  setup/crm_tag_multi_company_event_crm/setup.py
  setup/crm_tag_multi_company_sale/odoo/addons/crm_tag_multi_company_sale
  setup/crm_tag_multi_company_sale/setup.py
Labels: approved, bot is merging ⏳

#777 [16.0][MIG] login_all_company
  login_all_company/README.rst
  login_all_company/__init__.py
  login_all_company/__manifest__.py
  login_all_company/i18n/login_all_company.pot
  login_all_company/readme/CONTRIBUTORS.rst
  login_all_company/readme/DESCRIPTION.rst
  login_all_company/static/description/icon.png
  login_all_company/static/description/index.html
  login_all_company/static/src/js/company_service.esm.js
  setup/login_all_company/odoo/addons/login_all_company
  setup/login_all_company/setup.py
Labels: approved, bot is merging ⏳

#740 [16.0][IMP] product_category_company: allow the company to be false in search domain
  product_category_company/models/product_category.py
Labels: approved, ready to merge, bot is merging ⏳

#732 [FIX] stock_intercompany_bidirectional: Fix incorrect move warehouse
  stock_intercompany_bidirectional/__manifest__.py
  stock_intercompany_bidirectional/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#738 [FIX] account_invoice_inter_company : creating a credit note should g…
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#572 [16.0][ADD] purchase_sale_stock_inter_company_mrp
  purchase_sale_stock_inter_company/models/stock_picking.py
  purchase_sale_stock_inter_company_mrp/README.rst
  purchase_sale_stock_inter_company_mrp/__init__.py
  purchase_sale_stock_inter_company_mrp/__manifest__.py
  purchase_sale_stock_inter_company_mrp/models/__init__.py
  purchase_sale_stock_inter_company_mrp/models/stock_picking.py
  purchase_sale_stock_inter_company_mrp/readme/CONTRIBUTORS.rst
  purchase_sale_stock_inter_company_mrp/readme/DESCRIPTION.rst
  purchase_sale_stock_inter_company_mrp/static/description/icon.png
  purchase_sale_stock_inter_company_mrp/static/description/index.html
  purchase_sale_stock_inter_company_mrp/tests/__init__.py
  purchase_sale_stock_inter_company_mrp/tests/test_inter_company_purchase_sale_stock_mrp.py
  setup/purchase_sale_stock_inter_company_mrp/odoo/addons/purchase_sale_stock_inter_company_mrp
  setup/purchase_sale_stock_inter_company_mrp/setup.py
Labels: approved, bot is merging ⏳

#580 [16.0][ADD] sale_partner_company
  sale_partner_company/README.rst
  sale_partner_company/__init__.py
  sale_partner_company/__manifest__.py
  sale_partner_company/models/__init__.py
  sale_partner_company/models/res_partner.py
  sale_partner_company/models/sale_order.py
  sale_partner_company/readme/CONFIGURE.rst
  sale_partner_company/readme/CONTRIBUTORS.rst
  sale_partner_company/readme/DESCRIPTION.rst
  sale_partner_company/readme/USAGE.rst
  sale_partner_company/static/description/index.html
  sale_partner_company/tests/__init__.py
  sale_partner_company/tests/test_sale_partner_company.py
  sale_partner_company/views/partner_view.xml
  setup/sale_partner_company/odoo/addons/sale_partner_company
  setup/sale_partner_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#681 [16.0][MIG] calendar_event_type_multi_company: Migration to 16.0
  calendar_event_type_multi_company/README.rst
  calendar_event_type_multi_company/__init__.py
  calendar_event_type_multi_company/__manifest__.py
  calendar_event_type_multi_company/i18n/calendar_event_type_multi_company.pot
  calendar_event_type_multi_company/models/__init__.py
  calendar_event_type_multi_company/models/calendar_event_type.py
  calendar_event_type_multi_company/readme/CONTRIBUTORS.rst
  calendar_event_type_multi_company/readme/DESCRIPTION.rst
  calendar_event_type_multi_company/security/calendar_event_type.xml
  calendar_event_type_multi_company/static/description/icon.png
  calendar_event_type_multi_company/static/description/index.html
  calendar_event_type_multi_company/views/calendar_event_type.xml
  setup/calendar_event_type_multi_company/odoo/addons/calendar_event_type_multi_company
  setup/calendar_event_type_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#680 [16.0][MIG] calendar_event_multi_company: Migration to 16.0
  calendar_event_multi_company/README.rst
  calendar_event_multi_company/__init__.py
  calendar_event_multi_company/__manifest__.py
  calendar_event_multi_company/i18n/calendar_event_multi_company.pot
  calendar_event_multi_company/i18n/it.po
  calendar_event_multi_company/models/__init__.py
  calendar_event_multi_company/models/calendar_event.py
  calendar_event_multi_company/readme/CONTRIBUTORS.rst
  calendar_event_multi_company/readme/DESCRIPTION.rst
  calendar_event_multi_company/security/calendar_event.xml
  calendar_event_multi_company/static/description/icon.png
  calendar_event_multi_company/static/description/index.html
  calendar_event_multi_company/views/calendar_event.xml
  setup/calendar_event_multi_company/odoo/addons/calendar_event_multi_company
  setup/calendar_event_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#706 [16.0][MIG] ir_actions_report_multi_company: Migration from Odoo 13.0 to 16.0
  ir_actions_report_multi_company/README.rst
  ir_actions_report_multi_company/__init__.py
  ir_actions_report_multi_company/__manifest__.py
  ir_actions_report_multi_company/i18n/fr.po
  ir_actions_report_multi_company/i18n/ir_actions_report_multi_company.pot
  ir_actions_report_multi_company/models/__init__.py
  ir_actions_report_multi_company/models/ir_actions_actions.py
  ir_actions_report_multi_company/models/ir_actions_report.py
  ir_actions_report_multi_company/readme/CONTRIBUTORS.rst
  ir_actions_report_multi_company/readme/DESCRIPTION.rst
  ir_actions_report_multi_company/readme/USAGE.rst
  ir_actions_report_multi_company/security/multi_company.xml
  ir_actions_report_multi_company/static/description/icon.png
  ir_actions_report_multi_company/static/description/index.html
  ir_actions_report_multi_company/views/ir_actions_report_view.xml
  setup/ir_actions_report_multi_company/odoo/addons/ir_actions_report_multi_company
  setup/ir_actions_report_multi_company/setup.py
Labels: approved, bot is merging ⏳

#752 [18.0][MIG] res_company_code: Migration to 18.0
  res_company_code/README.rst
  res_company_code/__init__.py
  res_company_code/__manifest__.py
  res_company_code/demo/res_company.xml
  res_company_code/demo/res_groups.xml
  res_company_code/i18n/es.po
  res_company_code/i18n/fr.po
  res_company_code/i18n/it.po
  res_company_code/i18n/res_company_code.pot
  res_company_code/models/__init__.py
  res_company_code/models/ir_http.py
  res_company_code/models/res_company.py
  res_company_code/pyproject.toml
  res_company_code/readme/CONTRIBUTORS.md
  res_company_code/readme/DESCRIPTION.md
  res_company_code/static/description/icon.png
  res_company_code/static/description/index.html
  res_company_code/static/description/res_company_form.png
  res_company_code/static/description/res_company_tree.png
  res_company_code/static/description/switch_company_menu.png
  res_company_code/tests/__init__.py
  res_company_code/tests/test_res_company_code.py
  res_company_code/views/view_res_company.xml
Labels: approved, ready to merge, bot is merging ⏳

#759 [16.0][MIG] crm_lost_reason_multi_company
  crm_lost_reason_multi_company/README.rst
  crm_lost_reason_multi_company/__init__.py
  crm_lost_reason_multi_company/__manifest__.py
  crm_lost_reason_multi_company/i18n/crm_lost_reason_multi_company.pot
  crm_lost_reason_multi_company/models/__init__.py
  crm_lost_reason_multi_company/models/crm_lead.py
  crm_lost_reason_multi_company/models/crm_lost_reason.py
  crm_lost_reason_multi_company/readme/CONTRIBUTORS.rst
  crm_lost_reason_multi_company/readme/DESCRIPTION.rst
  crm_lost_reason_multi_company/security/crm_lost_reason.xml
  crm_lost_reason_multi_company/static/description/icon.png
  crm_lost_reason_multi_company/static/description/index.html
  crm_lost_reason_multi_company/views/crm_lost_reason.xml
  setup/crm_lost_reason_multi_company/odoo/addons/crm_lost_reason_multi_company
  setup/crm_lost_reason_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#758 [16.0][MIG] partner_category_multi_company
  partner_category_multi_company/README.rst
  partner_category_multi_company/__init__.py
  partner_category_multi_company/__manifest__.py
  partner_category_multi_company/i18n/hr.po
  partner_category_multi_company/i18n/pt.po
  partner_category_multi_company/i18n/res_partner_category_multi_company.pot
  partner_category_multi_company/models/__init__.py
  partner_category_multi_company/models/res_partner.py
  partner_category_multi_company/models/res_partner_category.py
  partner_category_multi_company/readme/CONTRIBUTORS.rst
  partner_category_multi_company/readme/DESCRIPTION.rst
  partner_category_multi_company/security/res_partner_category.xml
  partner_category_multi_company/static/description/icon.png
  partner_category_multi_company/static/description/index.html
  partner_category_multi_company/views/res_partner_category.xml
  partner_category_multi_company/views/res_partner_views.xml
  partner_category_multi_company_account/README.rst
  partner_category_multi_company_account/__init__.py
  partner_category_multi_company_account/__manifest__.py
  partner_category_multi_company_account/models/__init__.py
  partner_category_multi_company_account/models/account_reconcile_model.py
  partner_category_multi_company_account/readme/CONTRIBUTORS.rst
  partner_category_multi_company_account/readme/DESCRIPTION.rst
  partner_category_multi_company_account/static/description/icon.png
  partner_category_multi_company_account/static/description/index.html
  partner_category_multi_company_analytic/README.rst
  partner_category_multi_company_analytic/__init__.py
  partner_category_multi_company_analytic/__manifest__.py
  partner_category_multi_company_analytic/models/__init__.py
  partner_category_multi_company_analytic/models/analytic_distribution_model.py
  partner_category_multi_company_analytic/readme/CONTRIBUTORS.rst
  partner_category_multi_company_analytic/readme/DESCRIPTION.rst
  partner_category_multi_company_analytic/static/description/icon.png
  partner_category_multi_company_analytic/static/description/index.html
  partner_category_multi_company_analytic/views/analytic_distribution_model_views.xml
  setup/partner_category_multi_company/odoo/addons/partner_category_multi_company
  setup/partner_category_multi_company/setup.py
  setup/partner_category_multi_company_account/odoo/addons/partner_category_multi_company_account
  setup/partner_category_multi_company_account/setup.py
  setup/partner_category_multi_company_analytic/odoo/addons/partner_category_multi_company_analytic
  setup/partner_category_multi_company_analytic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#785 [17.0][IMP-FIX] partner_multi_company: no longer define display_name as store
  partner_multi_company/README.rst
  partner_multi_company/models/res_partner.py
  partner_multi_company/readme/CONTRIBUTORS.md
  partner_multi_company/static/description/index.html
Labels: approved, bot is merging ⏳

#788 [16.0][IMP] account_invoice_inter_company: move method _check_intercompany_…
  account_invoice_inter_company/__init__.py
  account_invoice_inter_company/models/__init__.py
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/models/res_company.py
  account_invoice_inter_company/models/res_config_settings.py
Labels: approved, bot is merging ⏳
