Repository OCA/multi-company, pull requests merged in 2025-08, with the labels that each got.

#865 [17.0][FWP][FIX] base_multi_company: support `in False` search operators
  base_multi_company/README.rst
  base_multi_company/hooks.py
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/readme/CONTRIBUTORS.md
  base_multi_company/readme/DEVELOPER.rst
  base_multi_company/static/description/index.html
  base_multi_company/tests/test_multi_company_abstract.py
  product_multi_company/README.rst
  product_multi_company/__init__.py
  product_multi_company/__manifest__.py
  product_multi_company/hooks.py
  product_multi_company/migrations/17.0.1.1.0/pre-migrate.py
  product_multi_company/models/__init__.py
  product_multi_company/models/product_product.py
  product_multi_company/readme/CONTRIBUTORS.md
  product_multi_company/static/description/index.html
  product_multi_company/tests/test_product_multi_company.py
Labels: approved, bot is merging ⏳

#866 [18.0][MIG] base_multi_company: Migration to 18.0
  base_multi_company/README.rst
  base_multi_company/__init__.py
  base_multi_company/__manifest__.py
  base_multi_company/hooks.py
  base_multi_company/i18n/base_multi_company.pot
  base_multi_company/i18n/es.po
  base_multi_company/i18n/es_AR.po
  base_multi_company/i18n/fr.po
  base_multi_company/i18n/hr.po
  base_multi_company/i18n/it.po
  base_multi_company/i18n/nl_NL.po
  base_multi_company/i18n/pt.po
  base_multi_company/i18n/pt_BR.po
  base_multi_company/i18n/zh_CN.po
  base_multi_company/models/__init__.py
  base_multi_company/models/base.py
  base_multi_company/models/multi_company_abstract.py
  base_multi_company/pyproject.toml
  base_multi_company/readme/CONTRIBUTORS.md
  base_multi_company/readme/DESCRIPTION.md
  base_multi_company/readme/DEVELOPER.rst
  base_multi_company/static/description/icon.png
  base_multi_company/static/description/index.html
  base_multi_company/tests/__init__.py
  base_multi_company/tests/multi_company_abstract_tester.py
  base_multi_company/tests/test_multi_company_abstract.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#798 [18.0][MIG] res_company_category: Migration to 18.0
  res_company_category/README.rst
  res_company_category/__init__.py
  res_company_category/__manifest__.py
  res_company_category/demo/res_company.xml
  res_company_category/demo/res_company_category.xml
  res_company_category/demo/res_groups.xml
  res_company_category/i18n/es.po
  res_company_category/i18n/fr.po
  res_company_category/i18n/it.po
  res_company_category/i18n/res_company_category.pot
  res_company_category/models/__init__.py
  res_company_category/models/res_company.py
  res_company_category/models/res_company_category.py
  res_company_category/pyproject.toml
  res_company_category/readme/CONFIGURE.md
  res_company_category/readme/CONTRIBUTORS.md
  res_company_category/readme/DESCRIPTION.md
  res_company_category/security/ir.model.access.csv
  res_company_category/static/description/icon.png
  res_company_category/static/description/index.html
  res_company_category/static/description/res_company_category_form.png
  res_company_category/static/description/res_company_category_tree.png
  res_company_category/static/description/res_company_form.png
  res_company_category/tests/__init__.py
  res_company_category/tests/test_res_company_category.py
  res_company_category/views/view_res_company.xml
  res_company_category/views/view_res_company_category.xml
Labels: bot is merging ⏳, stale

#870 [18.0] [MIG] partner_multi_company: Migration to 18.0
  partner_multi_company/README.rst
  partner_multi_company/__init__.py
  partner_multi_company/__manifest__.py
  partner_multi_company/hooks.py
  partner_multi_company/i18n/de.po
  partner_multi_company/i18n/es.po
  partner_multi_company/i18n/fr.po
  partner_multi_company/i18n/hr.po
  partner_multi_company/i18n/it.po
  partner_multi_company/i18n/partner_multi_company.pot
  partner_multi_company/i18n/pt.po
  partner_multi_company/models/__init__.py
  partner_multi_company/models/res_partner.py
  partner_multi_company/models/res_users.py
  partner_multi_company/pyproject.toml
  partner_multi_company/readme/CONTRIBUTORS.md
  partner_multi_company/readme/DESCRIPTION.md
  partner_multi_company/readme/INSTALL.md
  partner_multi_company/readme/ROADMAP.md
  partner_multi_company/readme/USAGE.md
  partner_multi_company/static/description/icon.png
  partner_multi_company/static/description/index.html
  partner_multi_company/tests/__init__.py
  partner_multi_company/tests/test_partner_multi_company.py
  partner_multi_company/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#872 [18.0][IMP] account_invoice_inter_company: propagate date to new invoice
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
Labels: approved, bot is merging ⏳

#837 [18.0][MIG] purchase_sale_inter_company: Migration to 18.0
  purchase_sale_inter_company/README.rst
  purchase_sale_inter_company/__init__.py
  purchase_sale_inter_company/__manifest__.py
  purchase_sale_inter_company/i18n/de.po
  purchase_sale_inter_company/i18n/es.po
  purchase_sale_inter_company/i18n/fr.po
  purchase_sale_inter_company/i18n/fr_FR.po
  purchase_sale_inter_company/i18n/it.po
  purchase_sale_inter_company/i18n/purchase_sale_inter_company.pot
  purchase_sale_inter_company/i18n/sl.po
  purchase_sale_inter_company/i18n/zh_CN.po
  purchase_sale_inter_company/models/__init__.py
  purchase_sale_inter_company/models/account_move.py
  purchase_sale_inter_company/models/purchase_order.py
  purchase_sale_inter_company/models/purchase_order_line.py
  purchase_sale_inter_company/models/res_company.py
  purchase_sale_inter_company/models/res_config.py
  purchase_sale_inter_company/models/sale_order.py
  purchase_sale_inter_company/models/sale_order_line.py
  purchase_sale_inter_company/pyproject.toml
  purchase_sale_inter_company/readme/CONFIGURE.md
  purchase_sale_inter_company/readme/CONTRIBUTORS.md
  purchase_sale_inter_company/readme/DESCRIPTION.md
  purchase_sale_inter_company/readme/INSTALL.md
  purchase_sale_inter_company/readme/ROADMAP.md
  purchase_sale_inter_company/static/description/icon.png
  purchase_sale_inter_company/static/description/index.html
  purchase_sale_inter_company/tests/__init__.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  purchase_sale_inter_company/views/res_config_view.xml
Labels: approved, bot is merging ⏳
