Repository OCA/multi-company, pull requests merged in 2025-07, with the labels that each got.

#853 [18.0][MIG] account_multicompany_easy_creation: Migration to 18.0
  account_multicompany_easy_creation/README.rst
  account_multicompany_easy_creation/__init__.py
  account_multicompany_easy_creation/__manifest__.py
  account_multicompany_easy_creation/i18n/account_multicompany_easy_creation.pot
  account_multicompany_easy_creation/i18n/es.po
  account_multicompany_easy_creation/i18n/it.po
  account_multicompany_easy_creation/models/__init__.py
  account_multicompany_easy_creation/models/res_company.py
  account_multicompany_easy_creation/pyproject.toml
  account_multicompany_easy_creation/readme/CONTRIBUTORS.md
  account_multicompany_easy_creation/readme/DESCRIPTION.md
  account_multicompany_easy_creation/readme/USAGE.md
  account_multicompany_easy_creation/security/ir.model.access.csv
  account_multicompany_easy_creation/static/description/icon.png
  account_multicompany_easy_creation/static/description/index.html
  account_multicompany_easy_creation/tests/__init__.py
  account_multicompany_easy_creation/tests/test_easy_creation.py
  account_multicompany_easy_creation/wizards/__init__.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.py
  account_multicompany_easy_creation/wizards/multicompany_easy_creation.xml
Labels: approved, bot is merging ⏳

#765 [17][FWD] account_invoice_inter_company : Ensure supplier reference is set in case the source invoice is the supplier one
  account_invoice_inter_company/models/account_move.py
Labels: bot is merging ⏳, stale

#757 [18.0][MIG] account_invoice_inter_company
  account_invoice_inter_company/README.rst
  account_invoice_inter_company/__init__.py
  account_invoice_inter_company/__manifest__.py
  account_invoice_inter_company/demo/inter_company_demo.xml
  account_invoice_inter_company/i18n/account_invoice_inter_company.pot
  account_invoice_inter_company/i18n/de.po
  account_invoice_inter_company/i18n/es.po
  account_invoice_inter_company/i18n/es_AR.po
  account_invoice_inter_company/i18n/fr.po
  account_invoice_inter_company/i18n/hr.po
  account_invoice_inter_company/i18n/it.po
  account_invoice_inter_company/i18n/zh_CN.po
  account_invoice_inter_company/models/__init__.py
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/models/res_company.py
  account_invoice_inter_company/models/res_config_settings.py
  account_invoice_inter_company/pyproject.toml
  account_invoice_inter_company/readme/CONFIGURE.md
  account_invoice_inter_company/readme/CONTRIBUTORS.md
  account_invoice_inter_company/readme/DESCRIPTION.md
  account_invoice_inter_company/readme/ROADMAP.md
  account_invoice_inter_company/static/description/icon.png
  account_invoice_inter_company/static/description/index.html
  account_invoice_inter_company/tests/__init__.py
  account_invoice_inter_company/tests/test_inter_company_invoice.py
  account_invoice_inter_company/views/account_move_views.xml
  account_invoice_inter_company/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#856 [17.0][MIG] purchase_sale_stock_inter_company: Migration to version 17.0
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
  purchase_sale_stock_inter_company/README.rst
  purchase_sale_stock_inter_company/__init__.py
  purchase_sale_stock_inter_company/__manifest__.py
  purchase_sale_stock_inter_company/demo/res_partner_demo.xml
  purchase_sale_stock_inter_company/i18n/de.po
  purchase_sale_stock_inter_company/i18n/es.po
  purchase_sale_stock_inter_company/i18n/fr.po
  purchase_sale_stock_inter_company/i18n/fr_FR.po
  purchase_sale_stock_inter_company/i18n/it.po
  purchase_sale_stock_inter_company/i18n/purchase_sale_stock_inter_company.pot
  purchase_sale_stock_inter_company/i18n/sl.po
  purchase_sale_stock_inter_company/i18n/zh_CN.po
  purchase_sale_stock_inter_company/models/__init__.py
  purchase_sale_stock_inter_company/models/purchase_order.py
  purchase_sale_stock_inter_company/models/res_company.py
  purchase_sale_stock_inter_company/models/res_config.py
  purchase_sale_stock_inter_company/models/stock_move_line.py
  purchase_sale_stock_inter_company/models/stock_picking.py
  purchase_sale_stock_inter_company/pyproject.toml
  purchase_sale_stock_inter_company/readme/CONFIGURE.md
  purchase_sale_stock_inter_company/readme/CONTRIBUTORS.md
  purchase_sale_stock_inter_company/readme/DESCRIPTION.md
  purchase_sale_stock_inter_company/readme/ROADMAP.md
  purchase_sale_stock_inter_company/static/description/icon.png
  purchase_sale_stock_inter_company/static/description/index.html
  purchase_sale_stock_inter_company/tests/__init__.py
  purchase_sale_stock_inter_company/tests/test_inter_company_purchase_sale_stock.py
  purchase_sale_stock_inter_company/views/res_config_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#748 [18.0][MIG] mail_multicompany: Migration to 18.0
  mail_multicompany/README.rst
  mail_multicompany/__init__.py
  mail_multicompany/__manifest__.py
  mail_multicompany/i18n/es.po
  mail_multicompany/i18n/it.po
  mail_multicompany/i18n/mail_multicompany.pot
  mail_multicompany/models/__init__.py
  mail_multicompany/models/ir_mail_server.py
  mail_multicompany/models/mail_message.py
  mail_multicompany/pyproject.toml
  mail_multicompany/readme/CONFIGURE.md
  mail_multicompany/readme/CONTRIBUTORS.md
  mail_multicompany/readme/DESCRIPTION.md
  mail_multicompany/readme/USAGE.md
  mail_multicompany/security/mail_security.xml
  mail_multicompany/static/description/icon.png
  mail_multicompany/static/description/index.html
  mail_multicompany/tests/__init__.py
  mail_multicompany/tests/test_mail_multicompany.py
  mail_multicompany/views/ir_mail_server_view.xml
Labels: bot is merging ⏳

#824 [MIG] crm_tag_multi_company: Migration to 18.0
  crm_tag_multi_company/README.rst
  crm_tag_multi_company/__init__.py
  crm_tag_multi_company/__manifest__.py
  crm_tag_multi_company/i18n/crm_tag_multi_company.pot
  crm_tag_multi_company/i18n/it.po
  crm_tag_multi_company/models/__init__.py
  crm_tag_multi_company/models/crm_lead.py
  crm_tag_multi_company/models/crm_tag.py
  crm_tag_multi_company/pyproject.toml
  crm_tag_multi_company/readme/CONTRIBUTORS.md
  crm_tag_multi_company/readme/DESCRIPTION.md
  crm_tag_multi_company/security/crm_tag.xml
  crm_tag_multi_company/static/description/icon.png
  crm_tag_multi_company/static/description/index.html
  crm_tag_multi_company/views/crm_tag.xml
Labels: approved, bot is merging ⏳

#813 [18.0][ADD] ir_ui_view_multi_company
  ir_ui_view_multi_company/README.rst
  ir_ui_view_multi_company/__init__.py
  ir_ui_view_multi_company/__manifest__.py
  ir_ui_view_multi_company/models/__init__.py
  ir_ui_view_multi_company/models/base.py
  ir_ui_view_multi_company/models/ir_ui_view.py
  ir_ui_view_multi_company/pyproject.toml
  ir_ui_view_multi_company/readme/CONFIGURE.md
  ir_ui_view_multi_company/readme/CONTEXT.md
  ir_ui_view_multi_company/readme/CONTRIBUTORS.md
  ir_ui_view_multi_company/readme/DESCRIPTION.md
  ir_ui_view_multi_company/static/description/index.html
  ir_ui_view_multi_company/tests/__init__.py
  ir_ui_view_multi_company/tests/test_ir_ui_view_multi_company.py
  ir_ui_view_multi_company/views/ir_ui_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#829 [18.0][MIG] calendar_event_type_multi_company
  calendar_event_type_multi_company/README.rst
  calendar_event_type_multi_company/__init__.py
  calendar_event_type_multi_company/__manifest__.py
  calendar_event_type_multi_company/i18n/calendar_event_type_multi_company.pot
  calendar_event_type_multi_company/i18n/it.po
  calendar_event_type_multi_company/models/__init__.py
  calendar_event_type_multi_company/models/calendar_event_type.py
  calendar_event_type_multi_company/pyproject.toml
  calendar_event_type_multi_company/readme/CONTRIBUTORS.md
  calendar_event_type_multi_company/readme/DESCRIPTION.md
  calendar_event_type_multi_company/security/calendar_event_type.xml
  calendar_event_type_multi_company/static/description/icon.png
  calendar_event_type_multi_company/static/description/index.html
  calendar_event_type_multi_company/views/calendar_event_type.xml
Labels: approved, bot is merging ⏳

#833 [18.0][MIG] ir_filters_multi_company
  ir_filters_multi_company/README.rst
  ir_filters_multi_company/__init__.py
  ir_filters_multi_company/__manifest__.py
  ir_filters_multi_company/hooks/post_init_hook.py
  ir_filters_multi_company/i18n/ir_filters_multi_company.pot
  ir_filters_multi_company/models/__init__.py
  ir_filters_multi_company/models/ir_filters.py
  ir_filters_multi_company/pyproject.toml
  ir_filters_multi_company/readme/CONTRIBUTORS.md
  ir_filters_multi_company/readme/DESCRIPTION.md
  ir_filters_multi_company/security/ir_filters.xml
  ir_filters_multi_company/static/description/icon.png
  ir_filters_multi_company/static/description/index.html
  ir_filters_multi_company/views/ir_filters.xml
Labels: approved, bot is merging ⏳

#864 [FIX] purchase_sale_inter_company: Create sale from other company
  purchase_sale_inter_company/models/purchase_order.py
  purchase_sale_inter_company/models/stock_picking.py
  purchase_sale_inter_company/tests/test_inter_company_purchase_sale.py
Labels: approved, bot is merging ⏳
