Repository OCA/multi-company, pull requests merged in 2025-03, with the labels that each got.

#789 [16.0][FIX][purchase_sale_stock_inter_company] synchronize inter-company picking qty
  purchase_sale_stock_inter_company/models/stock_picking.py
  purchase_sale_stock_inter_company/tests/test_inter_company_purchase_sale_stock.py
Labels: approved, bot is merging ⏳

#781 [16.0][FIX] account_invoice_inter_company: Adjust settings view to compatibilize with remove_odoo_enterprise
  account_invoice_inter_company/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#692 [16.0][ADD] mass_mailing_multi_company
  mass_mailing_multi_company/README.rst
  mass_mailing_multi_company/__init__.py
  mass_mailing_multi_company/__manifest__.py
  mass_mailing_multi_company/models/__init__.py
  mass_mailing_multi_company/models/mailing_contact.py
  mass_mailing_multi_company/models/mailing_contact_subscription.py
  mass_mailing_multi_company/models/mailing_list.py
  mass_mailing_multi_company/models/mailing_mailing.py
  mass_mailing_multi_company/readme/CONTRIBUTORS.rst
  mass_mailing_multi_company/readme/DESCRIPTION.rst
  mass_mailing_multi_company/security/mass_mailing.xml
  mass_mailing_multi_company/static/description/index.html
  mass_mailing_multi_company/tests/__init__.py
  mass_mailing_multi_company/tests/test_mass_mailing_multi_company.py
  mass_mailing_multi_company/views/mailing_contact_views.xml
  mass_mailing_multi_company/views/mailing_list_views.xml
  mass_mailing_multi_company/views/mailing_mailing_views.xml
  setup/mass_mailing_multi_company/odoo/addons/mass_mailing_multi_company
  setup/mass_mailing_multi_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#801 [15.0][ADD] product_multi_company_stock: do not allow to remove a company from company_ids if there is stock or moves in that company
  product_multi_company_stock/README.rst
  product_multi_company_stock/__init__.py
  product_multi_company_stock/__manifest__.py
  product_multi_company_stock/models/__init__.py
  product_multi_company_stock/models/product_template.py
  product_multi_company_stock/readme/CONTRIBUTORS.rst
  product_multi_company_stock/readme/DESCRIPTION.rst
  product_multi_company_stock/static/description/index.html
  product_multi_company_stock/tests/__init__.py
  product_multi_company_stock/tests/test_product_multi_company_stock.py
  setup/product_multi_company_stock/odoo/addons/product_multi_company_stock
  setup/product_multi_company_stock/setup.py
Labels: approved, bot is merging ⏳

#799 [OU][FIX][17.0]mail_multi_company: Prevent column creation if already exists
  mail_multicompany/migrations/17.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#805 [17.0][FW][IMP] account_invoice_inter_company: add setting to disable or enable intercompany invoicing
  account_invoice_inter_company/README.rst
  account_invoice_inter_company/models/account_move.py
  account_invoice_inter_company/models/res_company.py
  account_invoice_inter_company/models/res_config_settings.py
  account_invoice_inter_company/readme/CONFIGURE.md
  account_invoice_inter_company/static/description/index.html
  account_invoice_inter_company/tests/test_inter_company_invoice.py
  account_invoice_inter_company/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#778 [16.0][MIG] multicompany_configuration: Migration to 16.0
  multicompany_configuration/README.rst
  multicompany_configuration/__init__.py
  multicompany_configuration/__manifest__.py
  multicompany_configuration/i18n/es.po
  multicompany_configuration/i18n/multicompany_configuration.pot
  multicompany_configuration/models/__init__.py
  multicompany_configuration/models/multicompany_abstract.py
  multicompany_configuration/models/product_category.py
  multicompany_configuration/models/product_template.py
  multicompany_configuration/models/res_partner.py
  multicompany_configuration/readme/CONTRIBUTORS.rst
  multicompany_configuration/readme/DESCRIPTION.rst
  multicompany_configuration/static/description/icon.png
  multicompany_configuration/static/description/index.html
  multicompany_configuration/static/src/components/multicompany_data_field/multicompany_data_field.esm.js
  multicompany_configuration/static/src/components/multicompany_data_field/multicompany_data_field.xml
  multicompany_configuration/views/product_category.xml
  multicompany_configuration/views/product_product.xml
  multicompany_configuration/views/product_template.xml
  multicompany_configuration/views/res_partner.xml
  setup/multicompany_configuration/odoo/addons/multicompany_configuration
  setup/multicompany_configuration/setup.py
Labels: bot is merging ⏳
