Repository OCA/multi-company, pull requests merged in 2025-01, with the labels that each got.

#601 [16.0][MIG] ir_config_parameter_multi_company: Migration to 16.0
  ir_config_parameter_multi_company/README.rst
  ir_config_parameter_multi_company/__init__.py
  ir_config_parameter_multi_company/__manifest__.py
  ir_config_parameter_multi_company/i18n/es.po
  ir_config_parameter_multi_company/i18n/ir_config_parameter_multi_company.pot
  ir_config_parameter_multi_company/models/__init__.py
  ir_config_parameter_multi_company/models/ir_config_parameter.py
  ir_config_parameter_multi_company/readme/CONTRIBUTORS.rst
  ir_config_parameter_multi_company/readme/DESCRIPTION.rst
  ir_config_parameter_multi_company/security/parameter_security.xml
  ir_config_parameter_multi_company/static/description/icon.png
  ir_config_parameter_multi_company/static/description/index.html
  ir_config_parameter_multi_company/tests/__init__.py
  ir_config_parameter_multi_company/tests/test_ir_config_parameter_multi_company.py
  ir_config_parameter_multi_company/views/ir_config_parameter_view.xml
  setup/ir_config_parameter_multi_company/odoo/addons/ir_config_parameter_multi_company
  setup/ir_config_parameter_multi_company/setup.py
Labels: approved, bot is merging ⏳, stale

#248 [FIX] do not raise an error if user doesn't have access to any company
  res_company_code/models/ir_http.py
Labels: bot is merging ⏳, stale

#675 [16.0][ADD] pos_category_multicompany
  pos_category_multicompany/README.rst
  pos_category_multicompany/__init__.py
  pos_category_multicompany/__manifest__.py
  pos_category_multicompany/demo/res_groups.xml
  pos_category_multicompany/i18n/fr.po
  pos_category_multicompany/models/__init__.py
  pos_category_multicompany/models/pos_category.py
  pos_category_multicompany/readme/CONTRIBUTORS.rst
  pos_category_multicompany/readme/DESCRIPTION.rst
  pos_category_multicompany/security/ir_rule.xml
  pos_category_multicompany/static/description/index.html
  pos_category_multicompany/static/description/pos_category_multicompany.jpeg
  pos_category_multicompany/views/view_pos_category.xml
  setup/pos_category_multicompany/odoo/addons/pos_category_multicompany
  setup/pos_category_multicompany/setup.py
Labels: bot is merging ⏳

#701 [16] account_invoice_inter_company : Ensure supplier reference is set in case the source invoice is the supplier one
  account_invoice_inter_company/models/account_move.py
Labels: approved
